.Dd March 26, 2019
.Dt libfmapi 3
.Os libfmapi
.Sh NAME
.Nm libfmapi.h
.Nd Library to support the MAPI data types
.Sh SYNOPSIS
.In libfmapi.h
.Pp
Support functions
.Ft const char *
.Fn libfmapi_get_version "void"
.Pp
Error functions
.Ft void
.Fn libfmapi_error_free "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_error_fprint "libfmapi_error_t *error" "FILE *stream"
.Ft int
.Fn libfmapi_error_sprint "libfmapi_error_t *error" "char *string" "size_t size"
.Ft int
.Fn libfmapi_error_backtrace_fprint "libfmapi_error_t *error" "FILE *stream"
.Ft int
.Fn libfmapi_error_backtrace_sprint "libfmapi_error_t *error" "char *string" "size_t size"
.Pp
Entry identifier functions
.Ft int
.Fn libfmapi_entry_identifier_initialize "libfmapi_entry_identifier_t **entry_identifier" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_entry_identifier_free "libfmapi_entry_identifier_t **entry_identifier" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_entry_identifier_copy_from_byte_stream "libfmapi_entry_identifier_t *entry_identifier" "uint8_t *byte_stream" "size_t byte_stream_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_entry_identifier_get_service_provider_identifier "libfmapi_entry_identifier_t *entry_identifier" "uint8_t *guid_data" "size_t guid_data_size" "libfmapi_error_t **error"
.Pp
One-off entry identifier functions
.Ft int
.Fn libfmapi_one_off_entry_identifier_initialize "libfmapi_one_off_entry_identifier_t **entry_identifier" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_free "libfmapi_one_off_entry_identifier_t **entry_identifier" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_copy_from_byte_stream "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint8_t *byte_stream" "size_t byte_stream_size" "int ascii_codepage" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_version "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint16_t *format_version" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_flags "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint16_t *flags" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf8_display_name_size "libfmapi_one_off_entry_identifier_t *entry_identifier" "size_t *utf8_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf8_display_name "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint8_t *utf8_string" "size_t utf8_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf16_display_name_size "libfmapi_one_off_entry_identifier_t *entry_identifier" "size_t *utf16_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf16_display_name "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint16_t *utf16_string" "size_t utf16_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf8_address_type_size "libfmapi_one_off_entry_identifier_t *entry_identifier" "size_t *utf8_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf8_address_type "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint8_t *utf8_string" "size_t utf8_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf16_address_type_size "libfmapi_one_off_entry_identifier_t *entry_identifier" "size_t *utf16_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf16_address_type "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint16_t *utf16_string" "size_t utf16_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf8_email_address_size "libfmapi_one_off_entry_identifier_t *entry_identifier" "size_t *utf8_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf8_email_address "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint8_t *utf8_string" "size_t utf8_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf16_email_address_size "libfmapi_one_off_entry_identifier_t *entry_identifier" "size_t *utf16_string_size" "libfmapi_error_t **error"
.Ft int
.Fn libfmapi_one_off_entry_identifier_get_utf16_email_address "libfmapi_one_off_entry_identifier_t *entry_identifier" "uint16_t *utf16_string" "size_t utf16_string_size" "libfmapi_error_t **error"
.Sh DESCRIPTION
The
.Fn libfmapi_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return type.
For the actual return values see "libfmapi.h".
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh BUGS
Please report bugs of any kind on the project issue tracker: https://github.com/libyal/libfmapi/issues
.Sh AUTHOR
These man pages are generated from "libfmapi.h".
.Sh COPYRIGHT
Copyright (C) 2009-2021, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
the libfmapi.h include file
