= Message API (MAPI) definitions
Microsoft Outlook MAPI definitions for Exchange (ESEDB) and Outlook (NK2 and PFF) formats

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

The Microsoft (Office) Outlook Messaging API (MAPI) is used in multiple file formats.
This document is intended as a working document for the ESEDB, NK2 and PFF specification.

Which should allow existing Open Source forensic tooling to be able to process this file type.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Personal Folder File format.
| Classification: | Public
| Keywords: | MAPI, Message API
|===

[preface]
== License

....
Copyright (C) 2008-2022, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | January 2009 | Initial version based on PFF documentation.
| 0.0.2 | J.B. Metz | February 2009 | Added additional information.
| 0.0.3 | J.B. Metz | March 2009 | Added types encountered by C. Byington of the libpst project. +
Added long property types. +
Updated with information from libmapi-0.8.2 +
Worked on to dos.
| 0.0.4 | J.B. Metz | March 2009 | Additional information and corrections. +
Added NT security descriptor information. +
Additional information about several MAPI data types.
| 0.0.5 | J.B. Metz | April 2009 | Small fixes and additions.
| 0.0.6 | J.B. Metz | May 2009 | Update for recipient types based on patch by K. Mazur.
| 0.0.7 | J.B. Metz | May 2009 | Added information about MAPI X.400 object identifiers
| 0.0.8 | J.B. Metz | May 2009 | Added information about conversation index +
Update for multi value string based on patch by W. Brown
| 0.0.9 | J.B. Metz | June 2009 | Added information about MAPI definitions
| 0.0.10 | J.B. Metz | June 2009 | Corrected multi value for non variable sized types.
| 0.0.11 | J.B. Metz | July 2009 | Moved the NT security descriptor specification to a separate
document.
| 0.0.12 | J.B. Metz | July 2009 | Added information about MAPI definitions
| 0.0.13 | J.B. Metz | August 2009 | Correction for Conversation Index value. +
Added information about MAPI definitions
| 0.0.14 | J.B. Metz | September 2009 | Added information about invalid message body codepage.
| 0.0.15 | J.B. Metz | October 2009 | Additional findings.
| 0.0.16 | J.B. Metz | January 2010 | Additional findings from `[MS-PST]` +
Update value type identifiers to new format.
| 0.0.17 | J.B. Metz | April 2010 | Additional information about codepage 1200.
| 0.0.18 | J.B. Metz | June 2010 | Additional information about Exchange MAPI properties.
| 0.0.19 | J.B. Metz | July 2010 | Additional information about IPM classes.
| 0.0.20 | J.B. Metz | October 2010 | Additional information about one-off entry identifier
| 0.0.21 | J.B. Metz | January 2011 | License version update
Additional information about MAPI properties
| 0.0.22 | J.B. Metz | March 2012 | Moved locale identifier (LCID) to separate document.
| 0.0.23 | J.B. Metz | April 2012 | Small changes to codepage definitions
| 0.0.24 | J.B. Metz | May 2012 | Additional information.
| 0.0.25 | J.B. Metz | July 2012 | Email change.
| 0.0.26 | J.B. Metz | August 2012 | Updated references.
| 0.0.27 | J.B. Metz | February 2013 | Additional information.
| 0.0.28 | J.B. Metz | February 2013 | Additional information.
| 0.0.29 | J.B. Metz | August 2013 | Additional information with thanks to J. Lohman.
| 0.0.30 | J.B. Metz | November 2016 | Switched to asciidoc format.
| 0.0.31 | J.B. Metz | February | Migrated documentation and changes to formatting.
|===

:numbered:
== Overview

The Microsoft (Office) Outlook Messaging API (MAPI) is used in multiple file
formats. It is known to be used in the following file formats:

* Exchange MAPI database (MDB) on top of the Extensible Storage Engine Database format (EDB)
* Nickfile (NK2)
* Personal Folder File (PST, OST, PAB)

== Data types

The MAPI defines property data types. These are identified by Ptyp or PT_. In this document the
data types are referred to as value types.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | PtypUnspecified +
(PT_UNSPECIFIED, PT_UNKNOWN) | Reserved for interface use (type is not important to caller)
| 0x0001 | PtypNull +
(PT_NULL) | NULL (empty value)
| 0x0002 | PtypInteger16 +
(PT_SHORT, PT_I2) | Integer 16-bit signed
| 0x0003 | PtypInteger32 +
(PT_LONG, PT_I4) | Integer 32-bit signed
| 0x0004 | PtypFloating32 +
(PT_FLOAT, PT_R4) | Floating point single precision (32-bit)
| 0x0005 | PtypFloating64 +
(PT_DOUBLE, PT_R8) | Floating point double precision (64-bit)
| 0x0006 | PtypCurrency
(PT_CURRENCY) | Currency (64-bit) +
See section: <<currency,Currency>>
| 0x0007 | PtypFloatingTime +
(PT_APPTIME) | Floating (or application) Time (64-bit) +
The floating time is a double precision floating point and contains the whole number part represents the number of days since December 30, 1899, and the fractional part represents the fraction of a day since midnight.
| | |
| 0x000a | PtypErrorCode +
(PT_ERROR) | Error value (32-bit) +
SCODE +
See section: <<error_values,Error values (SCODE)>>
| | |
| 0x000b | PtypBoolean +
(PT_BOOLEAN) | Boolean +
0 == false, 0 != true +
Some Microsoft documentation states it to be 8-bit strictly using 0 = false and 1 = true
| | |
| 0x000d | PtypObject, PtypEmbeddedTable +
(PT_OBJECT) | Embedded COM object or table +
Variable of size
| | |
| 0x0014 | PtypInteger64
(PT_LONGLONG, PT_I8) | Integer 64-bit signed
| | |
| 0x001e | PtypString8 +
(PT_STRING8) | (extended) ASCII or Single Byte Character (SBC) string +
The string in the file is not always terminated by a end-of-string character +
The string is formatted using a code page.
| 0x001f | PtypString +
(PT_UNICODE) | Unicode string +
The string uses UTF-16 little-endian (LE) without the byte order mark (BOM) +
The string in the file is not always terminated by a end-of-string character
| | |
| 0x0040 | PtypTime +
(PT_SYSTIME) | Windows FILETIME or System Time (64-bit) +
See section: <<filetime,FILETIME>>
| | |
| 0x0048 | PtypGuid +
(PT_CLSID) | (OLE) GUID or Class identifier (128-bit) +
See section: <<guid,GUID>>
| | |
| 0x00fb | PtypServerId +
(PT_SVREID) | Server identifier
Variable of size +
Contains a 16-bit count followed by server identifier structure
| | |
| 0x00fd | PtypRestriction +
(PT_SRESTRICT) | Restriction +
Variable of size +
Contains an array of restriction structure
| 0x00fe | PtypRuleAction +
(PT_ACTIONS) | Rule actions +
Variable of size +
Contains a 16-bit count followed by rule actions structure
| | |
| 0x0102 | PtypBinary +
(PT_BINARY) | Binary data +
Variable of size
| | |
| 0x1002 | PtypMultipleInteger16 +
(PT_MV_SHORT, PT_MV_I2) | Array of Integer 16-bit signed values
| 0x1003 | PtypMultipleInteger32 +
(PT_MV_LONG, PT_MV_I4) | Array of Integer 32-bit signed values
| 0x1004 | PtypMultipleFloating32 +
(PT_MV_FLOAT, PT_MV_R4) | Array of Floating point single precision (32-bit) values
| 0x1005 | PtypMultipleFloating64 +
(PT_MV_DOUBLE, PT_MV_R8) | Array of Floating point double precision (64-bit) values
| 0x1006 | PtypMultipleCurrency +
(PT_MV_CURRENCY) | Array of Currency values
| 0x1007 | PtypMultipleFloatingTime +
(PT_MV_APPTIME) | Array of Floating time values
| | |
| 0x1014 | PtypMultipleInteger64 +
(PT_MV_LONGLONG, PT_MV_I8) | Array of Integer 64-bit signed values
| | |
| 0x101e | PtypMultipleString8 +
(PT_MV_STRING8) | Array of (extended) ASCII or SBC string values
| 0x101f | PtypMultipleString +
(PT_MV_UNICODE) | Array of Unicode (UTF-16 LE) string values
| | |
| 0x1040 | PtypMultipleTime +
(PT_MV_SYSTIME) | Array of Windows Filetime (64-bit) values
| | |
| 0x1048 | PtypMultipleGuid +
(PT_MV_CLSID) | Array of GUID (Class identifier) values
| | |
| 0x1102 | PtypMultipleBinary +
(PT_MV_BINARY) | Array of Binary data values
|===

....
0x1000 => Multi value flag
0x2000 => Multi instance flag
....

=== [[currency]]Currency

a 32-bit low part and a 32-bit high part
It contains a scaled integer representation of a decimal number with four digits to the right of the decimal point. For example, a stored value of 327500 represents a currency value of 32.7500.

=== [[filetime]]FILETIME

a 32-bit low part and a 32-bit high part
It contains the number of 100ns periods since January 1, 1601

=== [[guid]]GUID

Unsigned 32-bit Integer, Unsigned 16-bit Integer, Unsigned 16-bit Integer, 8 byte array

=== Array (multi) value types

The array (multi) value types are variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | The element data dependent on the size of the type
|===

The array (multi) value types of an ASCII and Unicode string and Binary Data
are variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | The number of elements
| 4 | (amount x 4) | | Byte offset of the element data
| ... | ... | | (The element data)
|===

The byte offsets can contain duplicate values. This is used to indicate
an empty value (NULL). Note that the array (multi) value type can consist
of a single element.

=== Server identifier structure

The server identifier refers to either a folder or message object. The server
identifier structure consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Structure definition used +
0x00 => custom definition +
0x01 => Microsoft definition
| 1 | 8 | | Folder identifier
| 9 | 8 | | Message identifier
| 17 | 4 | | Index within an array of server identifiers
|===

== The property identifiers

The MAPI defines property identifiers/names. These are identified by PidTag,
ptag or `PR_`. The property type is a combination of the item type and the item
value type. Transmittable properties are transferred with a message;
nontransmittable properties are not transferred with a message. Nontransmittable
properties usually contain information that is of value only to clients and
service providers operating with the current session.

[cols="1,5",options="header"]
|===
| Type | Description
| 0x0000 | Reserved for the special value PR_NULL (reserved by MAPI)
| 0x0001 – 0x0bff | Message envelope properties (defined by MAPI)
| 0x0c00 – 0x0dff | Recipient properties (defined by MAPI)
| 0x0e00 – 0x0fff | Non-transmittable message properties (defined by MAPI)
| 0x1000 – 0x2fff | Message content properties (defined by MAPI)
| 0x3000 - 0x33ff | Common object properties that appear on multiple objects (defined by MAPI)
| 0x3400 - 0x35ff | Message store properties (defined by MAPI)
| 0x3600 - 0x36ff | Folder and address book container properties (defined by MAPI)
| 0x3700 – 0x38ff | Attachment properties (defined by MAPI)
| 0x3900 – 0x39ff | Address book properties (defined by MAPI)
| 0x3a00 – 0x3bff | Messaging user properties (defined by MAPI)
| 0x3c00 – 0x3cff | Distribution list properties (defined by MAPI)
| 0x3d00 – 0x3dff | Profile properties (defined by MAPI)
| 0x3e00 – 0x3fff | Status object properties (defined by MAPI)
| 0x4000 - 0x57ff | Message envelope properties (defined by transport providers)
| 0x5800 – 0x5fff | Recipient properties (defined by transport and address book providers)
| 0x6000 - 0x65ff | Non-transmittable message properties (defined by clients)
| 0x6600 – 0x67ff | Non-transmittable properties (defined by a service provider) +
These properties can be visible or invisible to users.
| 0x67f0 – 0x67ff | Secure profile properties +
These properties can be hidden and encrypted.
| 0x6800 – 0x7bff | Message content properties for custom message classes (defined by creators of those classes)
| 0x7c00 – 0x7fff | Non-transmittable properties for custom message classes (defined by creators of those classes)
| 0x8000 – 0xfffe | Named properties (defined by clients and occasionally service providers) +
These properties are identified by name through the IMAPIProp::GetNamesFromIDs and IMAPIProp::GetIDsFromNames methods.
| 0xffff | Special error value PROP_ID_INVALID (reserved by MAPI)
|===

MAPI uses the `_A` and `_W` additives to signify if the property is an ASCII
(single byte character) or a Wide (multiple byte character) string. This
document does not bother with this distinction. The additive `_O` is used for
some types, it refers to the direct use of embedded object instead of data types.

=== Reserved (0x0000)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0000 | 0x0001 (NULL) | PidTagNull +
(PR_NULL) | NULL value +
Represents a null value or setting of a property or reserves array space.
|===

=== Message envelope properties (0x0001 – 0x0bff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0001 | 0x0003 (Integer 32-bit signed) | PidTagAcknowledgementMode +
(PR_ACKNOWLEDGEMENT_MODE) | Acknowledgment mode +
Contains the identifier of the mode for message acknowledgment. +
See section: <<acknowledgment_mode_definitions,Acknowledgment mode definitions>>
| 0x0002 | 0x000b (Boolean) | PidTagAlternateRecipientAllowed +
(PR_ALTERNATE_RECIPIENT_ALLOWED) | Alternate recipient allowed +
Contains TRUE if the sender permits auto forwarding of this message.
| | 0x001e (ASCII string) +
0x001f (Unicode string) | | [yellow-background]*Unknown*
| 0x0003 | 0x0102 (Binary data) | PidTagAuthorizingUsers +
(PR_AUTHORIZING_USERS) | Authorized users +
Contains a list of entry identifiers for users who have authorized the sending of a message.
| 0x0004 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagAutoForwardComment +
(PR_AUTO_FORWARD_COMMENT) | Auto forward comment +
Contains a comment added by the auto-forwarding agent.
| 0x0005 | 0x000b (Boolean) | PidTagAutoForwarded +
(PR_AUTO_FORWARDED) | Auto forwarded +
Contains TRUE if the client requests an X-MS-Exchange-Organization-AutoForwarded header field.
| 0x0006 | 0x0102 (Binary data) | PidTagContentConfidentialityAlgorithmId +
(PR_CONTENT_CONFIDENTIALITY_ALGORITHM_ID) | Content confidentiality algorithm identifier +
Contains an identifier for the algorithm used to confirm message content confidentiality.
| 0x0007 | 0x0102 (Binary data) | PidTagContentCorrelator +
(PR_CONTENT_CORRELATOR) | Original content correlator +
Contains a value the message sender can use to match a report with the original message.
| 0x0008 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagContentIdentifier +
(PR_CONTENT_IDENTIFIER) | Content identifier +
Contains a key value that enables the message recipient to identify its content.
| 0x0009 | | 0x0003 (Integer 32-bit signed) | PidTagContentLength +
(PR_CONTENT_LENGTH) | Content length +
Contains the message size in bytes.
| 0x000a | 0x000b (Boolean) | PidTagContentReturnRequested +
(PR_CONTENT_RETURN_REQUESTED) | Content return requested +
Contains TRUE if a message should be returned with a nondelivery report.
| 0x000b | 0x0102 (Binary data) | PidTagConversationKey +
(PR_CONVERSATION_KEY) | Conversation key +
Contains the mail conversation key which consists of a GUID
| 0x000c | 0x0102 (Binary data) | PidTagConversionEits +
(PR_CONVERSION_EITS) | Conversion encoded information types +
Contains the encoded information types (EITs) that are applied to a message in transit to describe conversions.
| 0x000d | 0x000b (Boolean) | PidTagConversionWithLossProhibited +
(PR_CONVERSION_WITH_LOSS_PROHIBITED) | Text conversions that loose information is prohibited
| 0x000e | 0x0102 (Binary data) | PidTagConvertedEits +
(PR_CONVERTED_EITS) | Encoded information types (EITS) conversation identifier +
Contains a conversion identifier for the types of text in a message.
| 0x000f | 0x0040 (Filetime) | PidTagDeferredDeliveryTime +
(PR_DEFERRED_DELIVERY_TIME) | Sender requested delivery date and time +
Contains the date and time when a message sender wants a message delivered.
| 0x0010 | 0x0040 (Filetime) | PidTagDeliverTime +
(PR_DELIVER_TIME) | Message delivery time +
Contains the date and time when the original message was delivered.
| 0x0011 | 0x0003 (Integer 32-bit signed) | PidTagDiscardReason +
(PR_DISCARD_REASON) | Message discard reason +
Contains a reason why a message transfer agent (MTA) has discarded a message.
| 0x0012 | 0x000b (Boolean) | PidTagDisclosureOfRecipients +
(PR_DISCLOSURE_OF_RECIPIENTS) | Disclosure of recipient allowed
| 0x0013 | 0x0102 (Binary data) | PidTagDistributionListExpansionHistory +
(PR_DL_EXPANSION_HISTORY) | Distribution list expansion history +
Contains a history showing how a distribution list has been expanded during message transmission.
| 0x0014 | 0x000b (Boolean) | PidTagDistributionListExpansionProhibited +
(PR_DL_EXPANSION_PROHIBITED) | Expansion of distribution list is prohibited
| 0x0015 | 0x0040 (Filetime) | PidTagExpiryTime +
(PR_EXPIRY_TIME) | Message expiry time +
Contains the date and time when the messaging system can invalidate the content of a message.
| 0x0016 | 0x000b (Boolean) | PidTagImplicitConversionProhibited +
(PR_IMPLICIT_CONVERSION_PROHIBITED) Implicit message text conversions prohibited
| 0x0017 | 0x0003 (Integer 32-bit signed) | PidTagImportance +
(PR_IMPORTANCE) | Importance +
Contains a value that indicates the message sender's opinion of the importance of a message. +
See section: <<importance_definitions,Importance definitions>>
| 0x0018 | | 0x0102 (Binary data) | PR_IPM_ID | Interpersonal message X400 identifier +
[yellow-background]*(No longer supported as of ...)*
| 0x0019 | 0x0040 (Filetime) | PidTagLatestDeliveryTime +
(PR_LATEST_DELIVERY_TIME) | Latest message delivery time +
Contains the latest date and time when a message transfer agent (MTA) should deliver a message.
| 0x001a | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagMessageClass +
(PR_MESSAGE_CLASS) | Message class +
Contains a text string that identifies the sender-defined message class. +
See section: <<message_class_definitions,Message class definitions>>
| | 0x0040 (Filetime) | | [yellow-background]*Unknown*
| 0x001b | 0x0102 (Binary data) | PidTagMessageDeliveryId +
(PR_MESSAGE_DELIVERY_ID) | Message delivery identifier
| 0x001b | 0x0102 (Binary data) | PidTagMessageDeliveryId +
(PR_MESSAGE_DELIVERY_ID) | Message delivery identifier
4+|
|===

* [yellow-background]*TODO: migrate documentation*

=== Recipient properties (0x0c00 – 0x0dff)

* [yellow-background]*TODO: migrate documentation*

=== Non-transmittable message properties (0x0e00 – 0x0fff)

* [yellow-background]*TODO: migrate documentation*

=== Message content properties (0x1000 – 0x2fff)

* [yellow-background]*TODO: migrate documentation*

=== Common objects properties (0x3000 – 0x03ff)

* [yellow-background]*TODO: migrate documentation*

=== Message store properties (0x3400 - 0x35ff)

* [yellow-background]*TODO: migrate documentation*

=== Folder and address book container properties (0x3600 – 0x36ff)

* [yellow-background]*TODO: migrate documentation*

=== Attachment properties (0x3700 – 0x38ff)

* [yellow-background]*TODO: migrate documentation*

=== Address book properties (0x3900 – 0x39ff)

* [yellow-background]*TODO: migrate documentation*

=== Messaging user properties (0x3a00 – 0x3bff)

* [yellow-background]*TODO: migrate documentation*

=== Distribution list properties (0x3c00 – 0x3cff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

=== Profile properties (0x3d00 – 0x3dff)

* [yellow-background]*TODO: migrate documentation*

=== Status object properties (0x3e00 – 0x3fff)

* [yellow-background]*TODO: migrate documentation*

=== Message envelope properties (0x4000 – 0x57ff)

* [yellow-background]*TODO: migrate documentation*

=== Recipient properties (0x5800 - 0x5fff)

* [yellow-background]*TODO: migrate documentation*

=== Non-transmittable message properties (0x6000 - 0x65ff)

* [yellow-background]*TODO: migrate documentation*

=== Non-transmittable properties (0x6600 – 0x67ff)

* [yellow-background]*TODO: migrate documentation*

=== Message content properties for custom message classes (0x6800 – 0x7bff)

* [yellow-background]*TODO: migrate documentation*

=== IPM.Microsoft.WunderBar.Link

* [yellow-background]*TODO: migrate documentation*

=== IPM.Microsoft.WunderBar.SFInfo

* [yellow-background]*TODO: migrate documentation*

=== IPM.RuleOrganizer

* [yellow-background]*TODO: migrate documentation*

=== Non-transmittable properties for custom message classes (0x7c00 – 0x7fff)

* [yellow-background]*TODO: migrate documentation*

=== IPM.Configuration

Found in:

* IPM.Configuration.AvailabilityOptions
* IPM.Configuration.Calendar
* IPM.Configuration.CategoryList
* IPM.Configuration.RssRule
* IPM.Configuration.WorkHours

* [yellow-background]*TODO: migrate documentation*

=== Named properties (0x8000 – 0xfffe)

* [yellow-background]*TODO: migrate documentation*

=== Special error value (0xffff)

* [yellow-background]*TODO: migrate documentation*

=== Named properties in the name-to-id map

* [yellow-background]*TODO: migrate documentation*

=== Class identifiers

* [yellow-background]*TODO: migrate documentation*

=== Calendar property set (0x0000000 - 0x00000ff)

* [yellow-background]*TODO: migrate documentation*

=== Address property set (0x0008000 - 0x00080ff)

* [yellow-background]*TODO: migrate documentation*

=== Task property set (0x0008100 - 0x00081ff)

* [yellow-background]*TODO: migrate documentation*

=== Appointment property set (0x0008200 - 0x00082ff)

* [yellow-background]*TODO: migrate documentation*

=== Common property set (0x0008500 - 0x00085ff)

* [yellow-background]*TODO: migrate documentation*

=== Journal property set (0x0008700 - 0x00087ff)

* [yellow-background]*TODO: migrate documentation*

=== RSS feed property set (0x0008900 - 0x00089ff)

* [yellow-background]*TODO: migrate documentation*

=== Sharing property set (0x0008a00 - 0x0008aff)

* [yellow-background]*TODO: migrate documentation*

=== Sticky note property set (0x0008b00 - 0x0008bff)

* [yellow-background]*TODO: migrate documentation*

=== Public strings property set

* [yellow-background]*TODO: migrate documentation*

=== Internet headers property set

* [yellow-background]*TODO: migrate documentation*

=== Attachment property set

* [yellow-background]*TODO: migrate documentation*

=== Unified messaging property set

* [yellow-background]*TODO: migrate documentation*

=== Other property sets

==== CLSID: 0006200b-0000-0000-c000-000000000046

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 00062013-0000-0000-c000-000000000046

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 00062014-0000-0000-c000-000000000046

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 29f3ab56-554d-11d0-a97c-00a0c911f50a

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 4e3a7680-b77a-11d0-9da5-00c04fd65685

* [yellow-background]*TODO: migrate documentation*

== MAPI definitions

=== [[acknowledgment_mode_definitions]]Acknowledgment mode definitions

The acknowledgment mode definitions are used by the following properties:

* 0x0001 (PidTagAcknowledgementMode)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | | Manual
| 1 | | Automatic
|===

=== [[importance_definitions]]Importance definitions

* [yellow-background]*TODO: migrate documentation*

=== [[priority_definitions]]Priority definitions

* [yellow-background]*TODO: migrate documentation*

=== [[sensitivity_definitions]]Sensitivity definitions

* [yellow-background]*TODO: migrate documentation*

=== [[address_type_definitions]]Address type definitions

* [yellow-background]*TODO: migrate documentation*

=== [[recipient_type_definitions]]Recipient type definitions

* [yellow-background]*TODO: migrate documentation*

=== [[message_flag_definitions]]Message flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[message_submit_flag_definitions]]Message submit flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[message_status_flag_definitions]]Message status flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[access_flags_definitions]]Access flags definitions

* [yellow-background]*TODO: migrate documentation*

=== [[row_type_definitions]]Row type definitions

* [yellow-background]*TODO: migrate documentation*

=== [[client_access_level_flags_definitions]]Client access level flags definitions

* [yellow-background]*TODO: migrate documentation*

=== [[icon_index_definitions]]Icon index definitions

* [yellow-background]*TODO: migrate documentation*

=== [[verb_definitions]]Verb definitions

* [yellow-background]*TODO: migrate documentation*

=== [[flag_status_definitions]]Flag status definitions

* [yellow-background]*TODO: migrate documentation*

=== [[resource_flag_definitions]]Resource flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[message_store_characteristics_mask_definitions]]Message store characteristics mask definitions

* [yellow-background]*TODO: migrate documentation*

=== [[valid_folder_mask_definitions]]Valid folder mask definitions

* [yellow-background]*TODO: migrate documentation*

=== [[container_flag_definitions]]Container flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[folder_type_definitions]]Folder type definitions

* [yellow-background]*TODO: migrate documentation*

=== [[aging_granularity_definitions]]Aging granularity definitions

* [yellow-background]*TODO: migrate documentation*

=== [[attachment_method_definitions]]Attachment method definitions

The attachment method definitions are used by the following properties:

* 0x3705 (PidTagAttachMethod)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | NO_ATTACHMENT | None (No attachment)
| 1 | ATTACH_BY_VALUE | By value +
The PR_ATTACH_DATA_BIN (PidTagAttachDataBinary) property contains the attachment data.
| 2 | ATTACH_BY_REFERENCE | By reference +
The PidTagAttachPathname (PR_ATTACH_PATHNAME) or PidTagAttachLongPathname  (PR_ATTACH_LONG_PATHNAME) property contains a fully-qualified path identifying the attachment to recipients with access to a common file server.
| 3 | ATTACH_BY_REF_RESOLVE | By reference resolve +
The PidTagAttachPathname (PR_ATTACH_PATHNAME) or PidTagAttachLongPathname  (PR_ATTACH_LONG_PATHNAME) property  contains a fully-qualified path identifying the attachment.
| 4 | ATTACH_BY_REF_ONLY | By reference only +
The PidTagAttachPathname (PR_ATTACH_PATHNAME) or PidTagAttachLongPathname  (PR_ATTACH_LONG_PATHNAME) property  contains a fully-qualified path identifying the attachment.
| 5 | ATTACH_EMBEDDED_MSG | Embedded message +
The PidTagAttachDataObject (PR_ATTACH_DATA_OBJ) property contains an embedded object that supports the IMessage interface.
| 6 | ATTACH_OLE | OLE +
The attachment is an embedded OLE object. +
When the OLE object is in OLE 2.0 IStorage format, the data is accessible through PidTagAttachDataObject (PR_ATTACH_DATA_OBJ). When the OLE object is in OLE 1.0 OLESTREAM format, the data is accessible through PR_ATTACH_DATA_BIN as an IStream. The type of the OLE encoding can be determined by the PidTagAttachTag (PR_ATTACH_TAG) value.
|===

=== [[attachment_flag_definitions]]Attachment flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[icon_display_type_definitions]]Icon display type definitions

* [yellow-background]*TODO: migrate documentation*

=== [[extended_icon_display_type_definitions]]Extended icon display type definitions

* [yellow-background]*TODO: migrate documentation*

=== [[gender_definitions]]Gender definitions

* [yellow-background]*TODO: migrate documentation*

=== [[encoding_preference_flag_definitions]]Encoding preference flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[codepage_definitions]]Codepage definitions

* [yellow-background]*TODO: migrate documentation*

=== [[conflict_resolution_method_definitions]]Conflict resolution method definitions

* [yellow-background]*TODO: migrate documentation*

=== [[message_editor_format_definitions]]Message editor format definitions

* [yellow-background]*TODO: migrate documentation*

=== [[rpc_over_http_flag_definitions]]RPC over HTTP flag definitions

* [yellow-background]*TODO: migrate documentation*

=== [[rpc_over_http_authentication_scheme_definitions]]RPC over HTTP authentication scheme definitions

* [yellow-background]*TODO: migrate documentation*

* [yellow-background]*TODO: migrate rest of documentation*

== MAPI data

=== [[message_body]] The message body

Both the plain text message body (PidTagBody) and the HTML message body
(PidTagBodyHtml) are stored using a codepage. The codepage (character set) used
can determined as following:

1. use the PidTagInternetCodepage if available
2. else use the PidTagMessageCodepage if available
3. else use the system codepage.

Note that some items do contain both a PidTagInternetCodepage and
PidTagMessageCodepage, but the PidTagMessageCodepage is used to code the plain
text message body (PidTagBody).

== Item classes

* [yellow-background]*TODO: migrate documentation*

=== [[object_type]]Object type

* [yellow-background]*TODO: migrate documentation*

=== [[container_class_definitions]]Container class definitions

* [yellow-background]*TODO: migrate documentation*

=== [[message_class_definitions]]Message class definitions

* [yellow-background]*TODO: migrate documentation*

== Other item classes

=== Name to identifier map

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0001 | 0x0003 (Integer 32-bit signed) | PidTagNameidBucketCount | Name-to-ID Map Number of Validation Entries +
[yellow-background]*(Hash bucket count)*
| 0x0002 | 0x0102 (Binary data) | PidTagNameidStreamGuid | Name-to-ID map Class Identifiers +
Contains the name-to-id map table class identifiers
| 0x0003 | 0x0102 (Binary data) | PidTagNameidStreamEntry | Name-to-ID map Entries +
Contains the name-to-id map table entries
| 0x0004 | 0x0102 (Binary data) | PidTagNameidStreamString | Name-to-ID map Strings +
Contains the name-to-id map table strings
| 0x1000 - 0xfffe | 0x0102 (Binary data) | PidTagNameidBucketBase | Name-to-ID Map Validation Entries +
[yellow-background]*(Hash buckets)* +
According to `[MS-PST]` a hash bucket can hold up to 8 validation entries
|===

== [[error_values]]Error values (SCODE)

Error values are stored in a SCODE structure. The SCODE structure is also known
as HRESULT.

The SCODE structure consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 (LSB) | 16 bits | | The error or warning code
| 2 | 11 bits | | Error facility
| 3.3 | 1 bit | | r-bit (Reserved)
| 3.4 | 1 bit | | N-bit (Reserved)
| 3.5 | 1 bit | | C-bit (Reserved)
| 3.6 | 1 bit | | R-bit (Reserved)
| 3.7 | 1 bit | | S-bit (success-bit) +
0 indicates success and 1 failure.
|===

=== Error facility definitions

The SCODE specifies error and warning values for different facilities:

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x000 | FACILITY_NULL | Used for broadly applicable common status codes such as S_OK or E_OUTOF_MEMORY.
| 0x001 | FACILITY_RPC | For status codes returned from remote procedure calls.
| 0x002 | FACILITY_DISPATCH | For late binding IDispatch interface errors.
| 0x003 | FACILITY_STORAGE | For status codes returned from IStorage or IStream method calls relating to structured storage. Status codes with code (lower 16 bits) values in the range of Windows error codes (that is, less than 256) have the same meaning as the corresponding Windows errors.
| 0x004 | FACILITY_ITF | For most status codes returned from interface methods; the value is defined by the interface. That is, two HRESULT values with exactly the same 32-bit value returned from two different interfaces might have different meanings.
3+|
| 0x008 | FACILITY_WINDOWS | 
3+|
| 0x010 | FACILITY_SCARD | 
| 0x011 | FACILITY_COMPLUS | 
3+|
| 0x019 | FACILITY_HTTP | 
| 0x020 | FACILITY_BACKGROUNDCOPY | 
3+|
| 0x026 | FACILITY_GRAPHICS | 
| 0x027 | FACILITY_NAP FACILITY_SHELL | 
| 0x028 | FACILITY_INK | 
3+|
| 0x030 | FACILITY_PLA | 
| 0x031 | FACILITY_FVE | 
| 0x032 | FACILITY_FWP | 
3+|
| 0x034 | FACILITY_NDIS | 
3+|
| 0x7ff | FACILITY_BACKUP | 
| 0x800 | FACILITY_NTDSB | 
|===

=== Error values

* [yellow-background]*TODO: complete documentation*

== Notes

* [yellow-background]*TODO: migrate rest of documentation*

:numbered!:
[appendix]
== References

`[SMITH02]`

[cols="1,5",options="header"]
|===
| Title: | outlook.pst -- format of MS Outlook .pst file
| Author(s): | David Smith, Joe Nahmias, Brad Hards, Carl Byington
| URL: | https://www.five-ten-sg.com/libpst/rn01re05.html
|===

`[RUSSON]`

[cols="1,5",options="header"]
|===
| Title: | NTFS Documentation
| Author(s): | Richard Russon, Yuval Flede
| URL: | https://dubeyko.com/development/FileSystems/NTFS/ntfsdoc.pdf
|===

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title: | Microsoft Developer Network
| URL: | http://msdn.microsoft.com/
|===

`[MS-OXCFXICS]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-OXCFXICS]`: Bulk Data Transfer Protocol Specification
| URL: | http://msdn.microsoft.com/
|===

`[MS-OXOAB]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-OXOAB]`: Offline Address Book (OAB) File Format and Schema
| URL: | http://msdn.microsoft.com/
|===

`[MS-OXORULE]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-OXORULE]`: E-Mail Rules Protocol Specification
| URL: | http://msdn.microsoft.com/
|===

`[MS-PST]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-PST]` Outlook Personal Folders File Format (.pst) structure specification
| URL: | http://msdn.microsoft.com/
|===

`[NTLCID]`

[cols="1,5",options="header"]
|===
| Tile: | Locale identifier (LCID) definitions
| URL: | https://github.com/libyal/libfwnt/blob/main/documentation/Language%20Code%20identifiers.asciidoc
|===

`[NTSID]`

[cols="1,5",options="header"]
|===
| Tile: | NT security descriptor definitions
| URL: | https://github.com/libyal/libfwnt/blob/main/documentation/Security%20Descriptor.asciidoc
|===

`[OPENCHANGE]`

[cols="1,5",options="header"]
|===
| Title: | Openchange MAPI library
| URL: | http://www.openchange.org/index.php
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

