= Message API (MAPI) definitions
Microsoft Outlook MAPI definitions for Exchange (ESEDB) and Outlook (NK2 and PFF) formats

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

The Microsoft (Office) Outlook Messaging API (MAPI) is used in multiple file formats.
This document is intended as a working document for the ESEDB, NK2 and PFF specification.

Which should allow existing Open Source forensic tooling to be able to process this file type.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Personal Folder File format.
| Classification: | Public
| Keywords: | MAPI, Message API
|===

[preface]
== License

....
Copyright (C) 2008-2022, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | January 2009 | Initial version based on PFF documentation.
| 0.0.2 | J.B. Metz | February 2009 | Added additional information.
| 0.0.3 | J.B. Metz | March 2009 | Added types encountered by C. Byington of the libpst project. +
Added long property types. +
Updated with information from libmapi-0.8.2 +
Worked on to dos.
| 0.0.4 | J.B. Metz | March 2009 | Additional information and corrections. +
Added NT security descriptor information. +
Additional information about several MAPI data types.
| 0.0.5 | J.B. Metz | April 2009 | Small fixes and additions.
| 0.0.6 | J.B. Metz | May 2009 | Update for recipient types based on patch by K. Mazur.
| 0.0.7 | J.B. Metz | May 2009 | Added information about MAPI X.400 object identifiers
| 0.0.8 | J.B. Metz | May 2009 | Added information about conversation index +
Update for multi value string based on patch by W. Brown
| 0.0.9 | J.B. Metz | June 2009 | Added information about MAPI definitions
| 0.0.10 | J.B. Metz | June 2009 | Corrected multi value for non variable sized types.
| 0.0.11 | J.B. Metz | July 2009 | Moved the NT security descriptor specification to a separate
document.
| 0.0.12 | J.B. Metz | July 2009 | Added information about MAPI definitions
| 0.0.13 | J.B. Metz | August 2009 | Correction for Conversation Index value. +
Added information about MAPI definitions
| 0.0.14 | J.B. Metz | September 2009 | Added information about invalid message body codepage.
| 0.0.15 | J.B. Metz | October 2009 | Additional findings.
| 0.0.16 | J.B. Metz | January 2010 | Additional findings from `[MS-PST]` +
Update value type identifiers to new format.
| 0.0.17 | J.B. Metz | April 2010 | Additional information about codepage 1200.
| 0.0.18 | J.B. Metz | June 2010 | Additional information about Exchange MAPI properties.
| 0.0.19 | J.B. Metz | July 2010 | Additional information about IPM classes.
| 0.0.20 | J.B. Metz | October 2010 | Additional information about one-off entry identifier
| 0.0.21 | J.B. Metz | January 2011 | License version update
Additional information about MAPI properties
| 0.0.22 | J.B. Metz | March 2012 | Moved locale identifier (LCID) to separate document.
| 0.0.23 | J.B. Metz | April 2012 | Small changes to codepage definitions
| 0.0.24 | J.B. Metz | May 2012 | Additional information.
| 0.0.25 | J.B. Metz | July 2012 | Email change.
| 0.0.26 | J.B. Metz | August 2012 | Updated references.
| 0.0.27 | J.B. Metz | February 2013 | Additional information.
| 0.0.28 | J.B. Metz | February 2013 | Additional information.
| 0.0.29 | J.B. Metz | August 2013 | Additional information with thanks to J. Lohman.
| 0.0.30 | J.B. Metz | November 2016 | Switched to asciidoc format.
| 0.0.31 | J.B. Metz | February 2022 | Migrated documentation and changes to formatting.
|===

:numbered:
== Overview

The Microsoft (Office) Outlook Messaging API (MAPI) is used in multiple file
formats. It is known to be used in the following file formats:

* Exchange MAPI database (MDB) on top of the Extensible Storage Engine Database format (EDB)
* Nickfile (NK2)
* Personal Folder File (PST, OST, PAB)

== Data types

The MAPI defines property data types. These are identified by Ptyp or PT_. In this document the
data types are referred to as value types.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | PtypUnspecified +
(PT_UNSPECIFIED, PT_UNKNOWN) | Reserved for interface use (type is not important to caller)
| 0x0001 | PtypNull +
(PT_NULL) | NULL (empty value)
| 0x0002 | PtypInteger16 +
(PT_SHORT, PT_I2) | Integer 16-bit signed
| 0x0003 | PtypInteger32 +
(PT_LONG, PT_I4) | Integer 32-bit signed
| 0x0004 | PtypFloating32 +
(PT_FLOAT, PT_R4) | Floating point single precision (32-bit)
| 0x0005 | PtypFloating64 +
(PT_DOUBLE, PT_R8) | Floating point double precision (64-bit)
| 0x0006 | PtypCurrency
(PT_CURRENCY) | Currency (64-bit) +
See section: <<currency,Currency>>
| 0x0007 | PtypFloatingTime +
(PT_APPTIME) | Floating (or application) Time (64-bit) +
The floating time is a double precision floating point and contains the whole number part represents the number of days since December 30, 1899, and the fractional part represents the fraction of a day since midnight.
| | |
| 0x000a | PtypErrorCode +
(PT_ERROR) | Error value (32-bit) +
SCODE +
See section: <<error_values,Error values (SCODE)>>
| | |
| 0x000b | PtypBoolean +
(PT_BOOLEAN) | Boolean +
0 == false, 0 != true +
Some Microsoft documentation states it to be 8-bit strictly using 0 = false and 1 = true
| | |
| 0x000d | PtypObject, PtypEmbeddedTable +
(PT_OBJECT) | Embedded COM object or table +
Variable of size
| | |
| 0x0014 | PtypInteger64
(PT_LONGLONG, PT_I8) | Integer 64-bit signed
| | |
| 0x001e | PtypString8 +
(PT_STRING8) | (extended) ASCII or Single Byte Character (SBC) string +
The string in the file is not always terminated by a end-of-string character +
The string is formatted using a code page.
| 0x001f | PtypString +
(PT_UNICODE) | Unicode string +
The string uses UTF-16 little-endian (LE) without the byte order mark (BOM) +
The string in the file is not always terminated by a end-of-string character
| | |
| 0x0040 | PtypTime +
(PT_SYSTIME) | Windows FILETIME or System Time (64-bit) +
See section: <<filetime,FILETIME>>
| | |
| 0x0048 | PtypGuid +
(PT_CLSID) | (OLE) GUID or Class identifier (128-bit) +
See section: <<guid,GUID>>
| | |
| 0x00fb | PtypServerId +
(PT_SVREID) | Server identifier
Variable of size +
Contains a 16-bit count followed by server identifier structure
| | |
| 0x00fd | PtypRestriction +
(PT_SRESTRICT) | Restriction +
Variable of size +
Contains an array of restriction structure
| 0x00fe | PtypRuleAction +
(PT_ACTIONS) | Rule actions +
Variable of size +
Contains a 16-bit count followed by rule actions structure
| | |
| 0x0102 | PtypBinary +
(PT_BINARY) | Binary data +
Variable of size
| | |
| 0x1002 | PtypMultipleInteger16 +
(PT_MV_SHORT, PT_MV_I2) | Array of Integer 16-bit signed values
| 0x1003 | PtypMultipleInteger32 +
(PT_MV_LONG, PT_MV_I4) | Array of Integer 32-bit signed values
| 0x1004 | PtypMultipleFloating32 +
(PT_MV_FLOAT, PT_MV_R4) | Array of Floating point single precision (32-bit) values
| 0x1005 | PtypMultipleFloating64 +
(PT_MV_DOUBLE, PT_MV_R8) | Array of Floating point double precision (64-bit) values
| 0x1006 | PtypMultipleCurrency +
(PT_MV_CURRENCY) | Array of Currency values
| 0x1007 | PtypMultipleFloatingTime +
(PT_MV_APPTIME) | Array of Floating time values
| | |
| 0x1014 | PtypMultipleInteger64 +
(PT_MV_LONGLONG, PT_MV_I8) | Array of Integer 64-bit signed values
| | |
| 0x101e | PtypMultipleString8 +
(PT_MV_STRING8) | Array of (extended) ASCII or SBC string values
| 0x101f | PtypMultipleString +
(PT_MV_UNICODE) | Array of Unicode (UTF-16 LE) string values
| | |
| 0x1040 | PtypMultipleTime +
(PT_MV_SYSTIME) | Array of Windows Filetime (64-bit) values
| | |
| 0x1048 | PtypMultipleGuid +
(PT_MV_CLSID) | Array of GUID (Class identifier) values
| | |
| 0x1102 | PtypMultipleBinary +
(PT_MV_BINARY) | Array of Binary data values
|===

....
0x1000 => Multi value flag
0x2000 => Multi instance flag
....

=== [[currency]]Currency

a 32-bit low part and a 32-bit high part
It contains a scaled integer representation of a decimal number with four digits to the right of the decimal point. For example, a stored value of 327500 represents a currency value of 32.7500.

=== [[filetime]]FILETIME

a 32-bit low part and a 32-bit high part
It contains the number of 100ns periods since January 1, 1601

=== [[guid]]GUID

Unsigned 32-bit Integer, Unsigned 16-bit Integer, Unsigned 16-bit Integer, 8 byte array

=== Array (multi) value types

The array (multi) value types are variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | The element data dependent on the size of the type
|===

The array (multi) value types of an ASCII and Unicode string and Binary Data
are variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | The number of elements
| 4 | (amount x 4) | | Byte offset of the element data
| ... | ... | | (The element data)
|===

The byte offsets can contain duplicate values. This is used to indicate
an empty value (NULL). Note that the array (multi) value type can consist
of a single element.

=== Server identifier structure

The server identifier refers to either a folder or message object. The server
identifier structure consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Structure definition used +
0x00 => custom definition +
0x01 => Microsoft definition
| 1 | 8 | | Folder identifier
| 9 | 8 | | Message identifier
| 17 | 4 | | Index within an array of server identifiers
|===

== The property identifiers

The MAPI defines property identifiers/names. These are identified by PidTag,
ptag or `PR_`. The property type is a combination of the item type and the item
value type. Transmittable properties are transferred with a message;
nontransmittable properties are not transferred with a message. Nontransmittable
properties usually contain information that is of value only to clients and
service providers operating with the current session.

[cols="1,5",options="header"]
|===
| Type | Description
| 0x0000 | Reserved for the special value PR_NULL (reserved by MAPI)
| 0x0001 – 0x0bff | Message envelope properties (defined by MAPI)
| 0x0c00 – 0x0dff | Recipient properties (defined by MAPI)
| 0x0e00 – 0x0fff | Non-transmittable message properties (defined by MAPI)
| 0x1000 – 0x2fff | Message content properties (defined by MAPI)
| 0x3000 - 0x33ff | Common object properties that appear on multiple objects (defined by MAPI)
| 0x3400 - 0x35ff | Message store properties (defined by MAPI)
| 0x3600 - 0x36ff | Folder and address book container properties (defined by MAPI)
| 0x3700 – 0x38ff | Attachment properties (defined by MAPI)
| 0x3900 – 0x39ff | Address book properties (defined by MAPI)
| 0x3a00 – 0x3bff | Messaging user properties (defined by MAPI)
| 0x3c00 – 0x3cff | Distribution list properties (defined by MAPI)
| 0x3d00 – 0x3dff | Profile properties (defined by MAPI)
| 0x3e00 – 0x3fff | Status object properties (defined by MAPI)
| 0x4000 - 0x57ff | Message envelope properties (defined by transport providers)
| 0x5800 – 0x5fff | Recipient properties (defined by transport and address book providers)
| 0x6000 - 0x65ff | Non-transmittable message properties (defined by clients)
| 0x6600 – 0x67ff | Non-transmittable properties (defined by a service provider) +
These properties can be visible or invisible to users.
| 0x67f0 – 0x67ff | Secure profile properties +
These properties can be hidden and encrypted.
| 0x6800 – 0x7bff | Message content properties for custom message classes (defined by creators of those classes)
| 0x7c00 – 0x7fff | Non-transmittable properties for custom message classes (defined by creators of those classes)
| 0x8000 – 0xfffe | Named properties (defined by clients and occasionally service providers) +
These properties are identified by name through the IMAPIProp::GetNamesFromIDs and IMAPIProp::GetIDsFromNames methods.
| 0xffff | Special error value PROP_ID_INVALID (reserved by MAPI)
|===

MAPI uses the `_A` and `_W` additives to signify if the property is an ASCII
(single byte character) or a Wide (multiple byte character) string. This
document does not bother with this distinction. The additive `_O` is used for
some types, it refers to the direct use of embedded object instead of data types.

=== Reserved (0x0000)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0000 | 0x0001 (NULL) | PidTagNull +
(PR_NULL) | NULL value +
Represents a null value or setting of a property or reserves array space.
|===

=== Message envelope properties (0x0001 – 0x0bff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0001 | 0x0003 (Integer 32-bit signed) | PidTagAcknowledgementMode +
(PR_ACKNOWLEDGEMENT_MODE) | Acknowledgment mode +
Contains the identifier of the mode for message acknowledgment. +
See section: <<acknowledgment_mode_definitions,Acknowledgment mode definitions>>
| 0x0002 | 0x000b (Boolean) | PidTagAlternateRecipientAllowed +
(PR_ALTERNATE_RECIPIENT_ALLOWED) | Alternate recipient allowed +
Contains TRUE if the sender permits auto forwarding of this message.
| | 0x001e (ASCII string) +
0x001f (Unicode string) | | [yellow-background]*Unknown*
| 0x0003 | 0x0102 (Binary data) | PidTagAuthorizingUsers +
(PR_AUTHORIZING_USERS) | Authorized users +
Contains a list of entry identifiers for users who have authorized the sending of a message.
| 0x0004 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagAutoForwardComment +
(PR_AUTO_FORWARD_COMMENT) | Auto forward comment +
Contains a comment added by the auto-forwarding agent.
| 0x0005 | 0x000b (Boolean) | PidTagAutoForwarded +
(PR_AUTO_FORWARDED) | Auto forwarded +
Contains TRUE if the client requests an X-MS-Exchange-Organization-AutoForwarded header field.
| 0x0006 | 0x0102 (Binary data) | PidTagContentConfidentialityAlgorithmId +
(PR_CONTENT_CONFIDENTIALITY_ALGORITHM_ID) | Content confidentiality algorithm identifier +
Contains an identifier for the algorithm used to confirm message content confidentiality.
| 0x0007 | 0x0102 (Binary data) | PidTagContentCorrelator +
(PR_CONTENT_CORRELATOR) | Original content correlator +
Contains a value the message sender can use to match a report with the original message.
| 0x0008 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagContentIdentifier +
(PR_CONTENT_IDENTIFIER) | Content identifier +
Contains a key value that enables the message recipient to identify its content.
| 0x0009 | 0x0003 (Integer 32-bit signed) | PidTagContentLength +
(PR_CONTENT_LENGTH) | Content length +
Contains the message size in bytes.
| 0x000a | 0x000b (Boolean) | PidTagContentReturnRequested +
(PR_CONTENT_RETURN_REQUESTED) | Content return requested +
Contains TRUE if a message should be returned with a nondelivery report.
| 0x000b | 0x0102 (Binary data) | PidTagConversationKey +
(PR_CONVERSATION_KEY) | Conversation key +
Contains the mail conversation key which consists of a GUID
| 0x000c | 0x0102 (Binary data) | PidTagConversionEits +
(PR_CONVERSION_EITS) | Conversion encoded information types +
Contains the encoded information types (EITs) that are applied to a message in transit to describe conversions.
| 0x000d | 0x000b (Boolean) | PidTagConversionWithLossProhibited +
(PR_CONVERSION_WITH_LOSS_PROHIBITED) | Text conversions that loose information is prohibited
| 0x000e | 0x0102 (Binary data) | PidTagConvertedEits +
(PR_CONVERTED_EITS) | Encoded information types (EITS) conversation identifier +
Contains a conversion identifier for the types of text in a message.
| 0x000f | 0x0040 (Filetime) | PidTagDeferredDeliveryTime +
(PR_DEFERRED_DELIVERY_TIME) | Sender requested delivery date and time +
Contains the date and time when a message sender wants a message delivered.
| 0x0010 | 0x0040 (Filetime) | PidTagDeliverTime +
(PR_DELIVER_TIME) | Message delivery time +
Contains the date and time when the original message was delivered.
| 0x0011 | 0x0003 (Integer 32-bit signed) | PidTagDiscardReason +
(PR_DISCARD_REASON) | Message discard reason +
Contains a reason why a message transfer agent (MTA) has discarded a message.
| 0x0012 | 0x000b (Boolean) | PidTagDisclosureOfRecipients +
(PR_DISCLOSURE_OF_RECIPIENTS) | Disclosure of recipient allowed
| 0x0013 | 0x0102 (Binary data) | PidTagDistributionListExpansionHistory +
(PR_DL_EXPANSION_HISTORY) | Distribution list expansion history +
Contains a history showing how a distribution list has been expanded during message transmission.
| 0x0014 | 0x000b (Boolean) | PidTagDistributionListExpansionProhibited +
(PR_DL_EXPANSION_PROHIBITED) | Expansion of distribution list is prohibited
| 0x0015 | 0x0040 (Filetime) | PidTagExpiryTime +
(PR_EXPIRY_TIME) | Message expiry time +
Contains the date and time when the messaging system can invalidate the content of a message.
| 0x0016 | 0x000b (Boolean) | PidTagImplicitConversionProhibited +
(PR_IMPLICIT_CONVERSION_PROHIBITED) | Implicit message text conversions prohibited
| 0x0017 | 0x0003 (Integer 32-bit signed) | PidTagImportance +
(PR_IMPORTANCE) | Importance +
Contains a value that indicates the message sender's opinion of the importance of a message. +
See section: <<importance_definitions,Importance definitions>>
| 0x0018 | 0x0102 (Binary data) | PR_IPM_ID | Interpersonal message X400 identifier +
[yellow-background]*(No longer supported as of ...)*
| 0x0019 | 0x0040 (Filetime) | PidTagLatestDeliveryTime +
(PR_LATEST_DELIVERY_TIME) | Latest message delivery time +
Contains the latest date and time when a message transfer agent (MTA) should deliver a message.
| 0x001a | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagMessageClass +
(PR_MESSAGE_CLASS) | Message class +
Contains a text string that identifies the sender-defined message class. +
See section: <<message_class_definitions,Message class definitions>>
| | 0x0040 (Filetime) | | [yellow-background]*Unknown*
| 0x001b | 0x0102 (Binary data) | PidTagMessageDeliveryId +
(PR_MESSAGE_DELIVERY_ID) | Message delivery identifier
| 0x001b | 0x0102 (Binary data) | PidTagMessageDeliveryId +
(PR_MESSAGE_DELIVERY_ID) | Message delivery identifier
4+|
| 0x001e | 0x0102 (Binary data) | PidTagMessageSecurityLabel +
(PR_MESSAGE_SECURITY_LABEL) | Message security label
| 0x001f | 0x0102 (Binary data) | PidTagObsoletedMessageIds +
(PR_OBSOLETED_IPMS) | Obsolete message identifiers +
Contains the identifiers of messages that this message supersedes. +
[yellow-background]*Search key format*
| 0x0020 | 0x0102 (Binary data) | PidTagOriginallyIntendedRecipientName +
(PR_ORIGINALLY_INTENDED_RECIPIENT_NAME) | Originally intended recipient name +
Contains the encoded name of the originally intended recipient of an autoforwarded message.
| 0x0021 | 0x0102 (Binary data) | PidTagOriginalEits +
(PR_ORIGINAL_EITS) | Message text original encoded information types (EITS)
| 0x0022 | 0x0102 (Binary data) | PidTagOriginatorCertificate +
(PR_ORIGINATOR_CERTIFICATE) | Originator certificate +
Contains an ASN.1 authentication certificate
| 0x0023 | 0x000b (Boolean) | PidTagOriginatorDeliveryReportRequested +
(PR_ORIGINATOR_DELIVERY_REPORT_REQUESTED) | Originator delivery report requested +
Contains TRUE if a message sender requests a delivery report for a particular recipient from the messaging system before the message is placed in the message store.
| | 0x0102 (Binary data) | | [yellow-background]*Unknown*
| 0x0024 | 0x0102 (Binary data) | PidTagOriginatorReturnAddress +
(PR_ORIGINATOR_RETURN_ADDRESS) | Originator return address +
Contains the binary-encoded return address of the message originator.
| 0x0025 | 0x0102 (Binary data) | PidTagParentKey +
(PR_PARENT_KEY) | Parent key +
Contains the search key that is used to correlate the original message and the reports about the original message. +
[yellow-background]*Contains a GUID*
| 0x0026 | 0x0003 (Integer 32-bit signed) | PidTagPriority +
(PR_PRIORITY) | Priority +
See section: <<priority_definitions,Priority definitions>>
| 0x0027 | 0x0102 (Binary data) | PidTagOriginCheck +
(PR_ORIGIN_CHECK) | Origin verification value +
Contains a binary verification value that enables a delivery report recipient to verify the origin of the original message.
| 0x0028 | 0x000b (Boolean) | PidTagProofOfSubmissionRequested +
(PR_PROOF_OF_SUBMISSION_REQUESTED) | ASN.1 proof of submission requested
| 0x0029 | 0x000b (Boolean) | PidTagReadReceiptRequested +
(PR_READ_RECEIPT_REQUESTED) | Read receipt requested +
Contains TRUE if a message sender wants the messaging system to generate a read report when the recipient has read a message.
| 0x002a | 0x0040 (Filetime) | PidTagReceiptTime +
(PR_RECEIPT_TIME) | Receipt time +
Contains the date and time a delivery report is generated.
| 0x002b | 0x000b (Boolean) | PidTagRecipientReassignmentProhibited +
(PR_RECIPIENT_REASSIGNMENT_PROHIBITED) | Recipient reassignment prohibited +
Specifies whether adding additional recipients, when forwarding the message, is prohibited for the e-mail message.
| 0x002c | 0x0102 (Binary data) | PR_REDIRECTION_HISTORY | [yellow-background]*Unknown*
| 0x002d | 0x0102 (Binary data) | PR_RELATED_IPMS | [yellow-background]*Unknown*
| 0x002e | 0x0003 (Integer 32-bit signed) | PidTagOriginalSensitivity +
(PR_ORIGINAL_SENSITIVITY) | Original sensitivity +
Contains the sensitivity value assigned by the sender of the first version of a message that is, the message before being forwarded or replied to. +
See section: <<sensitivity_definitions,Sensitivity definitions>>
| 0x002f | 0x001e (ASCII string) +
0x001f (Unicode string) | PR_LANGUAGES | [yellow-background]*Unknown*
| 0x0030 | 0x0040 (Filetime) | PidTagReplyTime +
(PR_REPLY_TIME) | Reply deadline +
Specifies the reply deadline on a message.
| 0x0031 | 0x0102 (Binary data) | PidTagReportTag +
(PR_REPORT_TAG) | Report tag +
Contains a binary tag value that the messaging system should copy to any report generated for the message.
| 0x0032 | 0x0040 (Filetime) | PR_REPORT_TIME | [yellow-background]*Unknown*
| 0x0033 | 0x000b (Boolean) | PR_RETURNED_IPM | [yellow-background]*Unknown*
| 0x0034 | 0x0003 (Integer 32-bit signed) | PidTagSecurity +
(PR_SECURITY) | Security +
[yellow-background]*Unknown, deprecated according to MSDN*
| | 0x0102 | | [yellow-background]*Unknown* +
Contains: 4 bytes unknown, 16 bytes GUID, 4 bytes unknown, ENTRYID?
| 0x0035 | 0x000b (Boolean) | PR_INCOMPLETE_COPY | [yellow-background]*Unknown*
| 0x0036 | 0x0003 (Integer 32-bit signed) | PidTagSensitivity +
(PR_SENSITIVITY) | Sensitivity +
Contains a value that indicates the message sender's opinion of the sensitivity of a message. +
See section: <<sensitivity_definitions,Sensitivity definitions>>
| 0x0037 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSubject +
(PR_SUBJECT) | Subject +
Contains the full subject of a message. +
The subject can start with 2 characters of control codes see section: <<subject_control_codes,Subject control codes>>
| 0x0038 | 0x0102 (Binary data) | PidTagSubjectMessageId +
(PR_SUBJECT_IPM) | Subject message identifier +
Contains a binary value that is copied from the message for which a report is being generated.
| 0x0039 | 0x0040 (Filetime) | PidTagClientSubmitTime +
(PR_CLIENT_SUBMIT_TIME) | Client submit time +
Contains the date and time the message sender submitted a message.
| 0x003a | 0x001e (ASCII string) +
0x001f (Unicode string) | PR_REPORT_NAME | [yellow-background]*Unknown*
| 0x003b | 0x001e (ASCII string) +
0x001f (Unicode string) | | [yellow-background]*Unknown*
| | 0x0102 (Binary data) | PidTagSentRepresentingSearchKey +
(PR_SENT_REPRESENTING_SEARCH_KEY) | Sent representing search key
Contains ASCII NUL-terminated string. +
Contains the search key for the messaging user represented by the sender.
| 0x003c | 0x0102 (Binary data) | PR_X400_CONTENT_TYPE | [yellow-background]*Unknown*
| 0x003d | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSubjectPrefix +
(PR_SUBJECT_PREFIX) | Subject prefix _
Contains a subject prefix that typically indicates some action on a message, such as "FW: " for forwarding.
| 0x003e | 0x0003 (Integer 32-bit signed) | PR_NON_RECEIPT_REASON | [yellow-background]*Unknown*
| 0x003f | 0x0102 (Binary data) | PidTagReceivedByEntryId +
(PR_RECEIVED_BY_ENTRYID) | Received by entry identifier +
Contains the entry identifier for the messaging user represented by the sender. +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0040 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagReceivedByName +
(PR_RECEIVED_BY_NAME) | Received by name
| 0x0041 | 0x0102 (Binary data) | PidTagSentRepresentingEntryId +
(PR_SENT_REPRESENTING_ENTRYID) | Sent representing entry identifier _
Contains recipient/sender structure +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0042 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSentRepresentingName +
(PR_SENT_REPRESENTING_NAME) | Sent representing name +
Contains the display name for the messaging user represented by the sender.
| 0x0043 | 0x0102 (Binary data) | PR_RCVD_REPRESENTING_ENTRYID | Received representing entry identifier +
Contains recipient/sender structure +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0044 | 0x001e (ASCII string) +
0x001f (Unicode string) | PR_RCVD_REPRESENTING_NAME | Received representing name
| 0x0045 | 0x0102 (Binary data) | PR_REPORT_ENTRYID | Report entry identifier +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0046 | 0x0102 (Binary data) | PR_READ_RECEIPT_ENTRYID | Read receipt entry identifier +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0047 | 0x0102 (Binary data) | PR_MESSAGE_SUBMISSION_ID | [yellow-background]*Unknown*
| 0x0048 | 0x0040 (Filetime) | PR_PROVIDER_SUBMIT_TIME | [yellow-background]*Unknown*
| 0x0049 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalSubject +
(PR_ORIGINAL_SUBJECT) | Original subject +
Contains the subject of an original message for use in a report about the message.
| 0x004a | 0x000b (Boolean) | PR_DISC_VAL | [yellow-background]*Unknown*
| 0x004b | 0x001e (ASCII string) +
0x001f (Unicode string) | PR_ORIG_MESSAGE_CLASS | [yellow-background]*Unknown*
| 0x004c | 0x0102 (Binary data) | PidTagOriginalAuthorEntryId +
(PR_ORIGINAL_AUTHOR_ENTRYID) | Original author entry identifier +
Contains the entry identifier of the author of the first version of a message, that is, the message before being forwarded or replied to. +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x004d | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalAuthorName +
(PR_ORIGINAL_AUTHOR_NAME) | Original author name +
Contains the display name of the author of the first version of a message, that is, the message before being forwarded or replied to.
| 0x004e | 0x0040 (Filetime) | PidTagOriginalSubmitTime +
(PR_ORIGINAL_SUBMIT_TIME) | Original submit time +
Contains the original submission date and time of the message in the report.
| 0x004f | 0x0102 (Binary data) | PR_REPLY_RECIPIENT_ENTRIES | Reply recipients entries +
[yellow-background]*Unknown contents*
| 0x0050 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagReplyRecipientEntries +
(PR_REPLY_RECIPIENT_NAMES) | Reply recipients names
| 0x0051 | 0x0102 (Binary data) | PR_RECEIVED_BY_SEARCH_KEY | Received by search key +
Contains ASCII string with end-of-string character
| 0x0052 | 0x0102 (Binary data) | PR_RCVD_REPRESENTING_SEARCH_KEY | Received representing search key +
Contains ASCII string with end-of-string character
| 0x0053 | 0x0102 (Binary data) | PR_READ_RECEIPT_SEARCH_KEY | [yellow-background]*Unknown*
| 0x0054 | 0x0102 (Binary data) | PR_REPORT_SEARCH_KEY | [yellow-background]*Unknown*
| 0x0055 | 0x0040 (Filetime) | PR_ORIGINAL_DELIVERY_TIME | [yellow-background]*Unknown*
| 0x0056 | 0x0102 (Binary data) | PR_ORIGINAL_AUTHOR_SEARCH_KEY | [yellow-background]*Unknown*
| 0x0057 | 0x000b (Boolean) | PidTagMessageToMe +
(PR_MESSAGE_TO_ME) | My address in To field +
Contains TRUE if this messaging user is specifically named as a primary (To) recipient of this message and is not part of a distribution list.
| 0x0058 | 0x000b (Boolean) | PidTagMessageCcMe +
(PR_MESSAGE_CC_ME) | My address in CC field +
Contains TRUE if this messaging user is specifically named as a carbon copy (CC) recipient of this message and is not part of a distribution list.
| 0x0059 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagMessageRecipientMe +
(PR_MESSAGE_RECIP_ME) | Message addressed to me +
Contains TRUE if this messaging user is specifically named as a primary (To), carbon copy (CC), or blind carbon copy (BCC) recipient of this message and is not part of a distribution list.
| 0x005a | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalSenderName +
(PR_ORIGINAL_SENDER_NAME) | Original sender name +
Contains the display name of the sender of the first version of a message, that is, the message before being forwarded or replied to.
| 0x005b | 0x0102 (Binary data) | PidTagOriginalSenderEntryId +
(PR_ORIGINAL_SENDER_ENTRYID) | Original sender entry identifier +
Contains the entry identifier of the sender of the first version of a message, that is, the message before being forwarded or replied to. +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x005c | 0x0102 (Binary data) | PidTagOriginalSenderSearchKey +
(PR_ORIGINAL_SENDER_SEARCH_KEY) | Original sender search key +
Contains the search key for the sender of the first version of a message, that is, the message before being forwarded or replied to.
| 0x005d | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalSentRepresentingName +
(PR_ORIGINAL_SENT_REPRESENTING_NAME) | Original sent representing name +
Contains the display name of the messaging user on whose behalf the original message was sent.
| 0x005e | 0x0102 (Binary data) | PidTagOriginalSentRepresentingEntryId +
(PR_ORIGINAL_SENT_REPRESENTING_ENTRYID) | Original sent representing entry identifier +
Contains the entry identifier of the messaging user on whose behalf the original message was sent.
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x005f | 0x0102 (Binary data) | PidTagOriginalSentRepresentingSearchKey +
(PR_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY) | Original sent representing search key +
Contains the search key of the messaging user on whose behalf the original message was sent.
| 0x0060 | 0x0040 (Filetime) | PidTagStartDate +
(PR_START_DATE) | Appointment start date and time +
Contains the starting date and time of an appointment as managed by a scheduling application.
| 0x0061 | 0x0040 (Filetime) | PidTagEndDate +
(PR_END_DATE) | Appointment end date and time +
Contains the ending date and time of an appointment as managed by a scheduling application.
| 0x0062 | 0x0003 (Integer 32-bit signed) | PidTagOwnerAppointmentId +
(PR_OWNER_APPT_ID) | Appointment owner identifier +
Contains an identifier for an appointment in the owner's schedule.
| 0x0063 | 0x000b (Boolean) | PidTagResponseRequested +
(PR_RESPONSE_REQUESTED) | Response requested +
Contains TRUE if the message sender wants a response to a meeting request.
| 0x0064 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSentRepresentingAddressType +
(PR_SENT_REPRESENTING_ADDRTYPE) | Sent representing address type +
Contains the address type for the messaging user who is represented by the sender. +
See section: <<address_type_definitions,Address type definitions>>
| 0x0065 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSentRepresentingEmailAddress +
(PR_SENT_REPRESENTING_EMAIL_ADDRESS) | Sent representing e-mail address +
Contains the e-mail address for the messaging user who is represented by the sender.
| 0x0066 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalSenderAddressType +
(PR_ORIGINAL_SENDER_ADDRTYPE) | Original sender address type +
Contains the address type of the sender of the first version of a message, that is, the message before being forwarded or replied to. +
See section: <<address_type_definitions,Address type definitions>>
| 0x0067 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalSenderEmailAddress +
(PR_ORIGINAL_SENDER_EMAIL_ADDRESS) | Original sender e-mail address +
Contains the e-mail address of the sender of the first version of a message, that is, the message before being forwarded or replied to.
| 0x0068 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalSentRepresentingAddressType +
(PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE) | Original sent representing address type +
Contains the address type of the messaging user on whose behalf the original message was sent. +
See section: <<address_type_definitions,Address type definitions>>
| 0x0069 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalSentRepresentingEmailAddress +
(PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS) | Original sent representing e-mail address +
Contains the e-mail address of the messaging user on whose behalf the original message was sent.
| | | |
| 0x0070 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagConversationTopic +
(PR_CONVERSATION_TOPIC) | Conversation topic +
Contains the topic of the first message in a conversation thread.
| 0x0071 | 0x0102 (Binary data) | PidTagConversationIndex +
(PR_CONVERSATION_INDEX) | Conversation index +
Contains a binary value that indicates the relative position of this message within a conversation thread. +
See section: <<conversation_index_structure,conversation index structure>>
| 0x0072 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalDisplayBcc +
(PR_ORIGINAL_DISPLAY_BCC) | Original display BCC +
Contains the display names of any blind carbon copy (BCC) recipients of the original message.
| 0x0073 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalDisplayCc +
(PR_ORIGINAL_DISPLAY_CC) | Original display CC +
Contains the display names of any carbon copy (CC) recipients of the original message.
| 0x0074 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalDisplayTo +
(PR_ORIGINAL_DISPLAY_TO) | Original display TO +
Contains the display names of the primary (To) recipients of the original message.
| 0x0075 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagReceivedByAddressType +
(PR_RECEIVED_BY_ADDRTYPE) | Received by address type +
Contains the e-mail address type, such as SMTP, for the messaging user who actually receives the message. +
See section: <<address_type_definitions,Address type definitions>>
| 0x0076 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagReceivedByEmailAddress +
(PR_RECEIVED_BY_EMAIL_ADDRESS) | Received by e-mail address +
Contains the e-mail address for the messaging user who receives the message.
| 0x0077 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagReceivedRepresentingAddressType +
(PR_RCVD_REPRESENTING_ADDRTYPE) | Received representing address type +
Contains the address type for the messaging user who is represented by the user actually receiving the message. +
See section: <<address_type_definitions,Address type definitions>>
| 0x0078 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagReceivedRepresentingEmailAddress +
(PR_RCVD_REPRESENTING_EMAIL_ADDRESS) | Received representing e-mail address +
Contains the e-mail address for the messaging user who is represented by the receiving user.
| 0x0079 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalAuthorAddressType +
(PR_ORIGINAL_AUTHOR_ADDRTYPE) | Original author address type +
Contains the address type of the author of the first version of a message, that is, the message before being forwarded or replied to.
See section: <<address_type_definitions,Address type definitions>>
| 0x007a | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginalAuthorEmailAddress +
(PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS) | Original author e-mail address +
Contains the e-mail address of the author of the first version of a message, that is, the message before being forwarded or replied to.
| 0x007b | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginallyIntendedRecipAddrtype +
(PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE) | Originally intended recipient address type +
Contains the address type of the originally intended recipient of an auto-forwarded message. +
See section: <<address_type_definitions,Address type definitions>>
| 0x007c | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagOriginallyIntendedRecipEmailAddress +
(PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS) | Originally intended recipient e-mail address +
Contains the e-mail address of the originally intended recipient of an autoforwarded message.
| 0x007d | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagTransportMessageHeaders +
(PR_TRANSPORT_MESSAGE_HEADERS) | Transport message headers +
Contains transport-specific message envelope information. These contain the SMTP e-mail headers.
| 0x007e | 0x0102 (Binary data) | PidTagDelegation +
(PR_DELEGATION) | Delegation +
[yellow-background]*Unknown, deprecated according to MSDN*
| 0x007f | 0x0102 (Binary data) | PidTagTnefCorrelationKey +
(PR_TNEF_CORRELATION_KEY) | TNEF correlation key +
Contains a value that correlates a Transport Neutral Encapsulation Format (TNEF) attachment with a message. +
[yellow-background]*Contains a single byte 0x00*
| 0x0080 | 0x001e (ASCII string) +
0x001f (Unicode string) | "displayed" | [yellow-background]*Unknown (found in a message delivery report item)*
| 0x0081 | 0x001e (ASCII string) +
0x001f (Unicode string) | "automatic-action/MDN-sent-automatically" | [yellow-background]*Unknown (found in a message delivery report item)*
| | | |
| 0x0083 | 0x101e (Array of ASCII string) +
0x101f (Array of Unicode string) | | [yellow-background]*Unknown (Contains sender name)*
| 0x0084 | 0x101e (Array of ASCII string) +
0x101f (Array of Unicode string) | | [yellow-background]*Unknown (Contains sender e-mail address)*
|===

=== Recipient properties (0x0c00 – 0x0dff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0c00 | 0x0102 (Binary data) | PR_CONTENT_INTEGRITY_CHECK | [yellow-background]*Unknown*
| 0x0c01 | 0x0003 (Integer 32-bit signed) | PR_EXPLICIT_CONVERSION | [yellow-background]*Unknown*
| 0x0c02 | 0x000b (Boolean) | PidTagIpmReturnRequested +
(PR_IPM_RETURN_REQUESTED) | Return report requested +
Contains TRUE if this message should be returned with a report.
| 0x0c03 | 0x0102 (Binary data) | PidTagMessageToken +
(PR_MESSAGE_TOKEN) | Message ASN.1 secutiry token
| 0x0c04 | 0x0003 (Integer 32-bit signed) | PR_NDR_REASON_CODE | [yellow-background]*Unknown*
| 0x0c05 | 0x0003 (Integer 32-bit signed) | PR_NDR_DIAG_CODE | [yellow-background]*Unknown*
| 0x0c06 | 0x000b (Boolean) | PR_NON_RECEIPT_NOTIFICATION_REQUESTED | [yellow-background]*Unknown (Non receipt notification requested)*
| 0x0c07 | 0x0003 (Integer 32-bit signed) | PR_DELIVERY_POINT | [yellow-background]*Unknown*
| 0x0c08 | 0x000b (Boolean) | PR_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED | [yellow-background]*Unknown (Originator non delivery report requested)*
| 0x0c09 | 0x0102 (Binary data) | PR_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT | [yellow-background]*Unknown*
| 0x0c0a | 0x000b (Boolean) | PR_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY | [yellow-background]*Unknown*
| 0x0c0b | 0x0003 (Integer 32-bit signed) | PR_PHYSICAL_DELIVERY_MODE | [yellow-background]*Unknown*
| 0x0c0c | 0x0003 (Integer 32-bit signed) | PR_PHYSICAL_DELIVERY_REPORT_REQUEST | [yellow-background]*Unknown*
| 0x0c0d | 0x0102 (Binary data) | PR_PHYSICAL_FORWARDING_ADDRESS | [yellow-background]*Unknown*
| 0x0c0e | 0x000b (Boolean) | PR_PHYSICAL_FORWARDING_ADDRESS_REQUESTED | [yellow-background]*Unknown*
| 0x0c0f | 0x000b (Boolean) | PR_PHYSICAL_FORWARDING_PROHIBITED | [yellow-background]*Unknown*
| 0x0c10 | 0x0102 (Binary data) | PR_PHYSICAL_RENDITION_ATTRIBUTES | [yellow-background]*Unknown*
| 0x0c11 | 0x0102 (Binary data) | PR_PROOF_OF_DELIVERY | [yellow-background]*Unknown*
| 0x0c12 | 0x000b (Boolean) | PR_PROOF_OF_DELIVERY_REQUESTED | [yellow-background]*Unknown*
| 0x0c13 | 0x0102 (Binary data) | PidTagRecipientCertificate +
(PR_RECIPIENT_CERTIFICATE) | Recipient certificate +
Contains an ASN.1 authentication certificate
| 0x0c14 | 0x001e (ASCII string) +
0x001f (Unicode string) | PR_RECIPIENT_NUMBER_FOR_ADVICE | [yellow-background]*Unknown*
| 0x0c15 | 0x0003 (Integer 32-bit signed) | PidTagRecipientType +
(PR_RECIPIENT_TYPE) | Recipient type +
Contains the recipient type for a message recipient. +
See section: <<recipient_type_definitions,Recipient type definitions>>
| 0x0c16 | 0x0003 (Integer 32-bit signed) | PR_REGISTERED_MAIL_TYPE | [yellow-background]*Unknown*
| 0x0c17 | 0x000b (Boolean) | PR_REPLY_REQUESTED | Reply requested
| 0x0c18 | 0x0003 (Integer 32-bit signed) | PR_REQUESTED_DELIVERY_METHOD | [yellow-background]*Unknown*
| 0x0c19 | 0x0102 (Binary data) | PidTagSenderEntryId +
(PR_SENDER_ENTRYID) | Sender entry identifier +
Contains the message sender's entry identifier. +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0c1a | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSenderName +
(PR_SENDER_NAME) | Sender name +
Contains the message sender's display name.
| 0x0c1b | 0x001e (ASCII string) +
0x001f (Unicode string) | PR_SUPPLEMENTARY_INFO | [yellow-background]*Unknown*
| 0x0c1c | 0x0003 (Integer 32-bit signed) | PR_TYPE_OF_MTS_USER | [yellow-background]*Unknown*
| 0x0c1d | 0x0102 (Binary data) | PidTagSenderSearchKey +
(PR_SENDER_SEARCH_KEY) | Sender search key +
Contains the message sender's search key. Contains ASCII NUL-terminated string
| 0x0c1e | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSenderAddressType +
(PR_SENDER_ADDRTYPE) | Sender address type +
Contains the message sender's e-mail address type. +
See section: <<address_type_definitions,Address type definitions>>
| 0x0c1f | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagSenderEmailAddress +
(PR_SENDER_EMAIL_ADDRESS) | Sender e-mail address +
Contains the message sender's e-mail address.
| 0x0c20 | 0x0003 (Integer 32-bit signed) | PR_NDR_STATUS_CODE | [yellow-background]*Unknown (None delivery status code)*
|===

=== Non-transmittable message properties (0x0e00 – 0x0fff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0e00 | 0x0014 (Integer 64-bit signed) | PidTagCurrentVersion +
(PR_CURRENT_VERSION) | Message store verion +
Contain the current version of a message store.
| 0x0e01 | 0x000b (Boolean) | PidTagDeleteAfterSubmit +
(PR_DELETE_AFTER_SUBMIT) | Delete after submit +
Contains TRUE if a client application wants MAPI to delete the associated message after submission.
| 0x0e02 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagDisplayBcc +
(PR_DISPLAY_BCC) | Display BCC +
Contains an ASCII list of the display names of any blind carbon copy (BCC) message recipients, separated by semicolons (;).
| 0x0e03 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagDisplayCc +
(PR_DISPLAY_CC) | Display CC +
Contains an ASCII list of the display names of any carbon copy (CC) message recipients, separated by semicolons (;). 
| 0x0e04 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagDisplayTo +
(PR_DISPLAY_TO) | Display To +
Contains a list of the display names of the primary (To) message recipients, separated by semicolons (;)
| 0x0e05 | 0x001e (ASCII string) +
0x001f (Unicode string) | PidTagParentDisplay +
(PR_PARENT_DISPLAY) | Parent display name +
Contains the display name of the folder where a message was found during a search.
| 0x0e06 | 0x0040 (Filetime) | PidTagOriginalDeliveryTime +
(PR_MESSAGE_DELIVERY_TIME) | Message delivery time +
Contains a copy of the original message's delivery date and time in a thread. 
| 0x0e07 | 0x0003 (Integer 32-bit signed) | PidTagMessageFlags +
(PR_MESSAGE_FLAGS) | Message flags +
Contains a bitmask of flags that indicate the origin and current state of a message. +
See section: <<message_flag_definitions,Message flag definitions>>
| 0x0e08 | 0x0003 (Integer 32-bit signed) | PidTagMessageSize +
(PR_MESSAGE_SIZE) | Message size +
Contains the sum, in bytes, of the sizes of all properties on a message object.
| | 0x0014 (Integer 64-bit signed) | PidTagMessageSizeExtended +
(PR_MESSAGE_SIZE_EXTENDED) | Message size +
Contains the sum, in bytes, of the sizes of all properties on a message object.
| 0x0e09 | 0x0102 (Binary data) | PidTagParentEntryId +
(PR_PARENT_ENTRYID) | Parent folder entry identifier +
Contains the entry identifier of the folder that contains a folder or message. +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0e0a | 0x0102 (Binary data) | PidTagSentMailEntryId +
(PR_SENTMAIL_ENTRYID) | Sent mail folder entry identifier +
Contains the entry identifier of the folder where the message should be moved after submission. +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0e0b | 0x000b (Boolean) | PidTagCorrelate +
(PR_CORRELATE) | Correlation requested +
Contains TRUE if the sender of a message requests the correlation feature of the messaging system.
| 0x0e0c | 0x0102 (Binary data) | PidTagCorrelateMtsid +
(PR_CORRELATE_MTSID) | Correlation  message transfer system identifier +
Contains the message transfer system (MTS) identifier used in correlating reports with sent messages
| 0x0e0e | 0x000b (Boolean) | PidTagDiscreteValues +
(PR_DISCRETE_VALUES) | Report applies to specific members only +
Contains TRUE if a nondelivery report applies only to discrete members of a distribution list rather than the entire list. 
| 0x0e0f | 0x000b (Boolean) | PidTagResponsibility +
(PR_RESPONSIBILITY) | Transport provider has responsibility +
Contains TRUE if some transport provider has already accepted responsibility for delivering the message to this recipient, and FALSE if the MAPI spooler considers that this transport provider should accept responsibility.
|===

* [yellow-background]*TODO: migrate documentation*

=== Message content properties (0x1000 – 0x2fff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

* [yellow-background]*TODO: migrate documentation*

=== Common objects properties (0x3000 – 0x03ff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

* [yellow-background]*TODO: migrate documentation*

=== Message store properties (0x3400 - 0x35ff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

* [yellow-background]*TODO: migrate documentation*

=== Folder and address book container properties (0x3600 – 0x36ff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

* [yellow-background]*TODO: migrate documentation*

=== Attachment properties (0x3700 – 0x38ff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

* [yellow-background]*TODO: migrate documentation*

=== Address book properties (0x3900 – 0x39ff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

* [yellow-background]*TODO: migrate documentation*

=== Messaging user properties (0x3a00 – 0x3bff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

* [yellow-background]*TODO: migrate documentation*

=== Distribution list properties (0x3c00 – 0x3cff)

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
|===

=== Profile properties (0x3d00 – 0x3dff)

* [yellow-background]*TODO: migrate documentation*

=== Status object properties (0x3e00 – 0x3fff)

* [yellow-background]*TODO: migrate documentation*

=== Message envelope properties (0x4000 – 0x57ff)

* [yellow-background]*TODO: migrate documentation*

=== Recipient properties (0x5800 - 0x5fff)

* [yellow-background]*TODO: migrate documentation*

=== Non-transmittable message properties (0x6000 - 0x65ff)

* [yellow-background]*TODO: migrate documentation*

=== Non-transmittable properties (0x6600 – 0x67ff)

* [yellow-background]*TODO: migrate documentation*

=== Message content properties for custom message classes (0x6800 – 0x7bff)

* [yellow-background]*TODO: migrate documentation*

=== IPM.Microsoft.WunderBar.Link

* [yellow-background]*TODO: migrate documentation*

=== IPM.Microsoft.WunderBar.SFInfo

* [yellow-background]*TODO: migrate documentation*

=== IPM.RuleOrganizer

* [yellow-background]*TODO: migrate documentation*

=== Non-transmittable properties for custom message classes (0x7c00 – 0x7fff)

* [yellow-background]*TODO: migrate documentation*

=== IPM.Configuration

Found in:

* IPM.Configuration.AvailabilityOptions
* IPM.Configuration.Calendar
* IPM.Configuration.CategoryList
* IPM.Configuration.RssRule
* IPM.Configuration.WorkHours

* [yellow-background]*TODO: migrate documentation*

=== Named properties (0x8000 – 0xfffe)

* [yellow-background]*TODO: migrate documentation*

=== Special error value (0xffff)

* [yellow-background]*TODO: migrate documentation*

=== Named properties in the name-to-id map

* [yellow-background]*TODO: migrate documentation*

=== Class identifiers

* [yellow-background]*TODO: migrate documentation*

=== Calendar property set (0x0000000 - 0x00000ff)

* [yellow-background]*TODO: migrate documentation*

=== Address property set (0x0008000 - 0x00080ff)

* [yellow-background]*TODO: migrate documentation*

=== Task property set (0x0008100 - 0x00081ff)

* [yellow-background]*TODO: migrate documentation*

=== Appointment property set (0x0008200 - 0x00082ff)

* [yellow-background]*TODO: migrate documentation*

=== Common property set (0x0008500 - 0x00085ff)

* [yellow-background]*TODO: migrate documentation*

=== Journal property set (0x0008700 - 0x00087ff)

* [yellow-background]*TODO: migrate documentation*

=== RSS feed property set (0x0008900 - 0x00089ff)

* [yellow-background]*TODO: migrate documentation*

=== Sharing property set (0x0008a00 - 0x0008aff)

* [yellow-background]*TODO: migrate documentation*

=== Sticky note property set (0x0008b00 - 0x0008bff)

* [yellow-background]*TODO: migrate documentation*

=== Public strings property set

* [yellow-background]*TODO: migrate documentation*

=== Internet headers property set

* [yellow-background]*TODO: migrate documentation*

=== Attachment property set

* [yellow-background]*TODO: migrate documentation*

=== Unified messaging property set

* [yellow-background]*TODO: migrate documentation*

=== Other property sets

==== CLSID: 0006200b-0000-0000-c000-000000000046

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 00062013-0000-0000-c000-000000000046

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 00062014-0000-0000-c000-000000000046

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 29f3ab56-554d-11d0-a97c-00a0c911f50a

* [yellow-background]*TODO: migrate documentation*

==== CLSID: 4e3a7680-b77a-11d0-9da5-00c04fd65685

* [yellow-background]*TODO: migrate documentation*

== MAPI definitions

=== [[acknowledgment_mode_definitions]]Acknowledgment mode definitions

The acknowledgment mode definitions are used by the following properties:

* 0x0001 (PidTagAcknowledgementMode)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | | Manual
| 1 | | Automatic
|===

=== [[importance_definitions]]Importance definitions

The importance definitions are used by the following properties:

* 0x0017 (PidTagImportance)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | IMPORTANCE_LOW | Low
| 1 | IMPORTANCE_NORMAL | Normal
| 2 | IMPORTANCE_HIGH | High
|===

=== [[priority_definitions]]Priority definitions

The priority definitions are used by the following properties:

* 0x0026 (PidTagPriority)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| -1 | PRIO_NONURGENT | Non urgent
| 0 | PRIO_NORMAL | Normal
| 1 | PRIO_URGENT | Urgent
|===

=== [[sensitivity_definitions]]Sensitivity definitions

The sensitivitiy definitions are used by the following properties:

* 0x002e (PidTagOriginalSensitivity)
* 0x0036 (PidTagSensitivity)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | SENSITIVITY_NONE | None
| 1 | SENSITIVITY_PERSONAL | Personal
| 2 | SENSITIVITY_PRIVATE | Private
| 3 | SENSITIVITY_COMPANY_CONFIDENTIAL | Company Confidential
|===

=== [[address_type_definitions]]Address type definitions

The address type definitions are used by the following properties:

* 0x0064 (PidTagSentRepresentingAddressType)
* 0x0066 (PidTagOriginalSenderAddressType)
* 0x0068 (PidTagOriginalSentRepresentingAddressType)
* 0x0075 (PidTagReceivedByAddressType)
* 0x0077 (PidTagReceivedRepresentingAddressType)
* 0x0079 (PidTagOriginalAuthorAddressType)
* 0x007b (PidTagOriginallyIntendedRecipAddrtype)
* 0x0c1e (PidTagSenderAddressType)
* 0x3002 (PidTagAddressType)

[cols="1,5",options="header"]
|===
| Value | Identifier | Description
| "EX" | ExChange address
| "FAX" | [yellow-background]*FAX number*
| "MHS" | [yellow-background]*X.400 Message Handling Service address*
| "PROFS" |
| "SMTP" | Simple Mail Transfer Protocol address
| "UNKNOWN" |
| "X400" | X.400 address
|===

The value string should contain only the uppercase alphabetic characters from
A through Z and the numbers from 0 through 9.

=== [[recipient_type_definitions]]Recipient type definitions

The recipient type definitions are used by the following properties:

* 0x0c15 (PidTagRecipientType)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | MAPI_ORIG | Originator +
The originator.
| 1 | MAPI_TO | To +
The recipient is a primary (To) recipient.
| 2 | MAPI_CC | CC +
The recipient is a carbon copy (CC) recipient, a recipient that receives a message in addition to the primary recipients.
| 3 | MAPI_BCC | BCC +
The recipient is a blind carbon copy (BCC) recipient. Primary and carbon copy recipients are unaware of the existence of BCC recipients.
3+| _Special purpose flags_
| 0x10000000 | MAPI_P1 | Resend +
The recipient did not successfully receive the message on the previous attempt.
| 0x80000000 | MAPI_SUBMITTED | Already processed +
The recipient has already received the message and does not need to receive it again.
|===

=== [[message_flag_definitions]]Message flag definitions

The message flag definitions are used by the following properties:

* 0x0e07 (PidTagMessageFlags)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0001 | MSGFLAG_READ | Read +
The message is marked as having been read.
| 0x0002 | MSGFLAG_UNMODIFIED | Unmodified +
The outgoing message has not been modified since the first time that it was saved; the incoming message has not been modified since it was delivered.
| 0x0004 | MSGFLAG_SUBMIT | Submit +
The message is marked for sending.
| 0x0008 | MSGFLAG_UNSENT | Unsent +
The message is still being composed.
| 0x0010 | MSGFLAG_HASATTACH | Has attachment(s) +
The message has at least one attachment.
| 0x0020 | MSGFLAG_FROMME | From Me +
The messaging user sending was the messaging user receiving the message.
| 0x0040 | MSGFLAG_ASSOCIATED | Associated +
The message is an associated message of a folder.
| 0x0080 | MSGFLAG_RESEND | Resend +
The message includes a request for a resend operation with a nondelivery report.
| 0x0100 | MSGFLAG_RN_PENDING | Read notification pending +
A read report needs to be sent for the message.
| 0x0200 | MSGFLAG_NRN_PENDING | Non-Read notification pending +
A nonread report needs to be sent for the message.
| | |
| 0x1000 | MSGFLAG_ORIGIN_X400 | Origin X.400 +
The incoming message arrived over an X.400 link.
| 0x2000 | MSGFLAG_ORIGIN_INTERNET | Origin Internet +
The incoming message arrived over the Internet.
| | |
| 0x8000 | MSGFLAG_ORIGIN_MISC_EXT | Origin external +
The incoming message arrived over an external link other than X.400 or the Internet.
|===

=== [[message_submit_flag_definitions]]Message submit flag definitions

The message submit flag definitions are used by the following properties:

* 0x0e14 (PidTagSubmitFlags)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | SUBMITFLAG_LOCKED | The MAPI spooler currently has the message locked.
| 0x00000002 | SUBMITFLAG_PREPROCESS | The message needs preprocessing.
|===

=== [[message_status_flag_definitions]]Message status flag definitions

The message status flag definitions are used by the following properties:

* 0x0e17 (PidTagMessageStatus)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | MSGSTATUS_HIGHLIGHTED | The message is to be highlighted in recipients' folder displays.
| 0x00000002 | MSGSTATUS_TAGGED | The message has been tagged for a client-defined purpose.
| 0x00000004 | MSGSTATUS_HIDDEN | The message is to be suppressed from recipients' folder displays.
| 0x00000008 | MSGSTATUS_DELMARKED | The message has been marked for subsequent deletion.
| | |
| 0x00000100 | MSGSTATUS_DRAFT | The message is in draft revision status.
| 0x00000200 | MSGSTATUS_ANSWERED | The message has been replied to.
| | |
| 0x00001000 | MSGSTATUS_REMOTE_DOWNLOAD | The message has been marked for downloading from the remote message store to the local client.
| 0x00002000 | MSGSTATUS_REMOTE_DELETE | The message has been marked for deletion at the remote message store without downloading to the local client.
|===

=== [[access_flags_definitions]]Access flags definitions

The access flags definitions are used by the following properties:

* 0x0ff4 (PidTagAccess)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | MAPI_ACCESS_MODIFY | Write access
| 0x00000002 | MAPI_ACCESS_READ | Read access
| 0x00000004 | MAPI_ACCESS_DELETE | Deletion permission
| 0x00000008 | MAPI_ACCESS_CREATE_HIERARCHY | Permission to create sub folders in the folder hierarchy
| 0x00000010 | MAPI_ACCESS_CREATE_CONTENTS | Permission to create content messages
| 0x00000020 | MAPI_ACCESS_CREATE_ASSOCIATED | Permission to create associated content messages
|===

=== [[row_type_definitions]]Row type definitions

The row type definitions are used by the following properties:

* 0x0ff5 (PidTagRowType)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | TBL_LEAF_ROW | Data row
| 0x00000002 | TBL_EMPTY_CATEGORY | Header row with empty category
| 0x00000004 | TBL_EXPANDED_CATEGORY | Expanded header row
| 0x00000008 | TBL_COLLAPSED_CATEGORY | Collapsed header row
|===

=== [[client_access_level_flags_definitions]]Client access level flags definitions

The client access level flags definitions are used by the following properties:

* 0x0ff7 (PidTagAccessLevel)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | | Read-only
| 0x00000001 | | Modify
|===

=== [[icon_index_definitions]]Icon index definitions

The icon index definitions are used by the following properties:

* 0x1080 (PidTagIconIndex)

[cols="1,5",options="header"]
|===
| Value | Description
| 0x00000001 | Post
| |
| 0x00000003 | Other
| |
| 0x00000100 | Read mail
| 0x00000101 | Unread mail
| 0x00000102 | Submitted mail
| 0x00000103 | Unsent mail
| 0x00000104 | Receipt mail
| 0x00000105 | Replied mail
| 0x00000106 | Forwarded mail
| 0x00000107 | Remote mail
| 0x00000108 | Delivery mail
| 0x00000109 | Read mail
| 0x0000010a | Nondelivery mail
| 0x0000010b | Nonread mail
| 0x0000010c | Recall_S mail
| 0x0000010d | Recall_F mail
| 0x0000010e | Tracking mail
| |
| 0x0000011b | Out of office mail
| 0x0000011c | Recall mail
| |
| 0x00000130 | Tracked mail
| |
| 0x00000200 | Contact
| |
| 0x00000202 | Distribution list
| |
| 0x00000300 | Sticky note blue
| 0x00000301 | Sticky note green
| 0x00000302 | Sticky note pink
| 0x00000303 | Sticky note yellow
| 0x00000304 | Sticky note white
| |
| 0x00000400 | Single instance appointment
| 0x00000401 | Recurring appointment
| 0x00000402 | Single instance meeting
| 0x00000403 | Recurring meeting
| 0x00000404 | Meeting request
| 0x00000405 | Accept
| 0x00000406 | Decline
| 0x00000407 | Tentativly
| 0x00000408 | Cancellation
| 0x00000409 | Informational update
| |
| 0x00000500 | Task/Task Update
| 0x00000501 | Unassigned recurring task
| 0x00000502 | Assignee's task
| 0x00000503 | Assigner's task
| 0x00000504 | Task request
| 0x00000505 | Task acceptance
| 0x00000506 | Task rejection
| |
| 0x00000601 | Journal conversation
| 0x00000602 | Journal e-mail message
| 0x00000603 | Journal meeting request
| 0x00000604 | Journal meeting response
| |
| 0x00000606 | Journal task request
| 0x00000607 | Journal task response
| 0x00000608 | Journal note
| 0x00000609 | Journal fax
| 0x0000060a | Journal phone call
| |
| 0x0000060c | Journal letter
| 0x0000060d | Journal Microsoft Office Word
| 0x0000060e | Journal Microsoft Office Excel
| 0x0000060f | Journal Microsoft Office PowerPoint
| 0x00000610 | Journal Microsoft Office Access
| |
| 0x00000612 | Journal document
| 0x00000613 | Journal meeting
| 0x00000614 | Journal meeting cancellation
| 0x00000615 | Journal remote session
| |
| 0xffffffff | New mail
|===

=== [[verb_definitions]]Verb definitions

The verb definition are used by the following properties:

* 0x1081 (PidTagLastVerbExecuted)

Note that these values are not the same as the <<icon_index_definitions,Icon index definitions>>

[cols="1,5",options="header"]
|===
| Value | Description
| 0x00000001 | Post
| |
| 0x00000003 | Other
| |
| 0x00000100 | Read mail
| 0x00000101 | Unread mail
| 0x00000102 | Submitted mail
| 0x00000103 | Unsent mail
| 0x00000104 | Receipt mail
| 0x00000105 | Replied mail
| 0x00000106 | Forwarded mail
| 0x00000107 | Remote mail
| 0x00000108 | Delivery Receipt (Delivery mail)
| 0x00000109 | Read Receipt (Read mail)
| 0x0000010a | Nondelivery Receipt (Nondelivery mail)
| 0x0000010b | Nonread Receipt (Nonread mail)
| 0x0000010c | Recall_S mail
| 0x0000010d | Recall_F mail
| 0x0000010e | Tracking mail
| |
| 0x0000011b | Out of office mail
| 0x0000011c | Recall mail
| |
| 0x00000139 | Tracked mail
| |
| 0x00000200 | Contact
| 0x00000201 | Distribution list
| |
| 0x00000300 | Sticky note blue
| 0x00000301 | Sticky note green
| 0x00000302 | Sticky note pink
| 0x00000303 | Sticky note yellow
| 0x00000304 | Sticky note white
| |
| 0x00000400 | Single instance appointment
| 0x00000401 | Recurring appointment
| 0x00000402 | Single instance meeting
| 0x00000403 | Recurring meeting
| 0x00000404 | Meeting request / Full Update
| 0x00000405 | Accept
| 0x00000406 | Decline
| 0x00000407 | Tentatively Accept
| 0x00000408 | Cancellation
| 0x00000409 | Informational update
| |
| 0x00000500 | Task/Task Update
| 0x00000501 | Unassigned recurring task
| 0x00000502 | Assignee's task
| 0x00000503 | Assigner's task
| 0x00000504 | Task request
| 0x00000505 | Task acceptance
| 0x00000506 | Task rejection
| |
| 0x00000601 | Journal conversation
| 0x00000602 | Journal e-mail message
| 0x00000603 | Journal meeting request
| 0x00000604 | Journal meeting response
| |
| 0x00000606 | Journal task request
| 0x00000607 | Journal task response
| 0x00000608 | Journal note
| 0x00000609 | Journal fax
| 0x0000060a | Journal phone call
| 0x0000060b | Journal Task
| 0x0000060c | Journal letter
| 0x0000060d | Journal Microsoft Office Word
| 0x0000060e | Journal Microsoft Office Excel
| 0x0000060f | Journal Microsoft Office PowerPoint
| 0x00000610 | Journal Microsoft Office Access
| |
| 0x00000612 | Journal document
| 0x00000613 | Journal meeting
| 0x00000614 | Journal meeting cancellation
| 0x00000615 | Journal remote session
| |
| 0xffffffff | New mail
|===

=== [[flag_status_definitions]]Flag status definitions

The resource flag definitions are used by the following properties:

* 0x1090 (PidTagFlagStatus)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | | Unflagged
| 0x00000001 | followupComplete | Flagged complete
| 0x00000002 | followupFlagged | Flagged
|===

=== [[resource_flag_definitions]]Resource flag definitions

The resource flag definitions are used by the following properties:

* 0x3009 (PidTagResourceFlags)

For a message service:

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | SERVICE_DEFAULT_STORE | The message service contains the default store.
| 0x00000002 | SERVICE_SINGLE_COPY | Any attempt to create or copy this message service into a profile where the service already exists will fail.
| 0x00000004 | SERVICE_CREATE_WITH_STORE | Reserved
| 0x00000008 | SERVICE_PRIMARY_IDENTITY | The corresponding message service contains the provider used for the primary identity for this session.
| | |
| 0x00000020 | SERVICE_NO_PRIMARY_IDENTITY | Set to indicate that none of the providers in the message service can be used to supply an identity.
|===

For a service provider:

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | STATUS_DEFAULT_OUTBOUND | This identity should be applied to outbound messages if the profile contains multiple instances of this transport provider.
| 0x00000002 | STATUS_DEFAULT_STORE | This message store is the default store for the profile.
| 0x00000004 | STATUS_PRIMARY_IDENTITY | This provider furnishes the primary identity for the session.
| 0x00000008 | STATUS_SIMPLE_STORE | This message store will be used by Simple MAPI as its default message store.
| 0x00000010 | STATUS_XP_PREFER_LAST | This transport expects to be the last transport selected to send a message when multiple transport providers are able to transmit the message.
| 0x00000020 | STATUS_NO_PRIMARY_IDENTITY | This provider does not furnish an identity in its status row.
| 0x00000040 | STATUS_NO_DEFAULT_STORE | This message store is incapable of becoming the default message store for the profile.
| 0x00000080 | STATUS_TEMP_SECTION | This message store should not be published in the message store table and will be deleted from the profile after logoff.
| 0x00000100 | STATUS_OWN_STORE | This transport provider is tightly coupled with a message store and furnishes the PR_OWN_STORE_ENTRYID  (PidTagOwnStoreEntryId) property in its status row.
| 0x00000200 | HOOK_INBOUND | The spooler hook needs to process inbound messages.
| 0x00000400 | HOOK_OUTBOUND | The spooler hook needs to process outbound messages.
| 0x00000800 | STATUS_NEED_IPM_TREE | The standard folders in this message store, including the interpersonal message (IPM) root folder, have not yet been verified.
| 0x00001000 | STATUS_PRIMARY_STORE | This message store is to be used when a client application logs on.
| 0x00002000 | STATUS_SECONDARY_STORE | This message store is to be used if the primary store is not available when a client application logs on.
|===

=== [[message_store_characteristics_mask_definitions]]Message store characteristics mask definitions

The message store characteristics maskdefinitions are used by the following properties:

* 0x340d (PidTagStoreSupportMask)
* 0x6611 (PidTagContactAddressBookStoreSupportMask)
* 0x6621 (PidTagContactAddressBookStoreSupportMasks)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | STORE_ENTRYID_UNIQUE | Entry identifiers for the objects in the message store are unique, that is, never reused during the life of the store.
| 0x00000002 | STORE_READONLY | All interfaces for the message store have a read-only access level.
| 0x00000004 | STORE_SEARCH_OK | The message store supports search-results folders.
| 0x00000008 | STORE_MODIFY_OK | The message store supports modification of its existing messages.
| 0x00000010 | STORE_CREATE_OK | The message store supports creation of new messages.
| 0x00000020 | STORE_ATTACH_OK | The message store supports attachments (OLE or non-OLE) to messages.
| 0x00000040 | STORE_OLE_OK | The message store supports OLE attachments. The OLE data is accessible through an IStorage interface, such as that available through the PidTagAttachDataObject (PR_ATTACH_DATA_OBJ) property.
| 0x00000080 | STORE_SUBMIT_OK | The message store supports marking a message for submission.
| 0x00000100 | STORE_NOTIFY_OK | The message store supports notifications.
| 0x00000200 | STORE_MV_PROPS_OK | The message store supports multivalued properties, guarantees the stability of value order in a multivalued property throughout a save operation, and supports instantiation of multivalued properties in tables
| 0x00000400 | STORE_CATEGORIZE_OK | The message store supports categorized views of tables.
| 0x00000800 | STORE_RTF_OK | The message store supports Rich Text Format (RTF) messages, usually compressed, and the store itself keeps PR_BODY and PR_RTF_COMPRESSED synchronized.
| 0x00001000 | STORE_RESTRICTION_OK | The message store supports restrictions.
| 0x00002000 | STORE_SORT_OK | The message store supports sorting views of tables.
| 0x00004000 | STORE_PUBLIC_FOLDERS | The folders in this store are public (multi-user), not private (possibly multi-instance but not multi-user).
| 0x00008000 | STORE_UNCOMPRESSED_RTF | The message store supports storage of RTF messages in uncompressed form. An uncompressed RTF stream is identified by the value dwMagicUncompressedRTF in the stream header. The dwMagicUncompressedRTF value is defined in the RTFLIB.H file.
| 0x00010000 | STORE_HTML_OK | The message store supports HTML messages, stored in the PidTagBodyHtml (PR_BODY_HTML)  property.
| 0x00020000 | STORE_ANSI_OK | The message store supports properties containing ANSI (8-bit) characters.
| 0x00040000 | STORE_UNICODE_OK | The message store supports properties containing Unicode characters.
| 0x00080000 | STORE_LOCALSTORE | This flag is reserved and should not be used.
| | |
| 0x00200000 | STORE_ITEMPROC | In a wrapped PST store, indicates that when a new message arrives at the store, the store does rules and spam filter processing on the message separately. The store calls IMAPISupport::Notify, setting fnevNewMail in the NOTIFICATION structure that is passed as a parameter, and then passes the details of the new message to the listening client. Subsequently, when the listening client receives the notification, it does not process rules on the message.
| | |
| 0x00800000 | STORE_PUSHER_OK | The MAPI Protocol Handler will not crawl the store, and the store is responsible to push any changes through notifications to the indexer to have messages indexed.
|===

=== [[valid_folder_mask_definitions]]Valid folder mask definitions

The valid folder mask definitions are used by the following properties:

* 0x35df (PidTagValidFolderMask)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0001 | FOLDER_IPM_SUBTREE_VALID | The IPM folder subtree has a valid entry identifier.
| 0x0002 | FOLDER_IPM_INBOX_VALID | The interpersonal message (IPM) receive folder has a valid entry identifier.
| 0x0004 | FOLDER_IPM_OUTBOX_VALID | The IPM Outbox folder has a valid entry identifier
| 0x0008 | FOLDER_IPM_WASTEBOX_VALID | The IPM Deleted Items folder has a valid entry identifier.
| 0x0010 | FOLDER_IPM_SENTMAIL_VALID | The IPM Sent Items folder has a valid entry identifier.
| 0x0020 | FOLDER_VIEWS_VALID | The views folder has a valid entry identifier.
| 0x0040 | FOLDER_COMMON_VIEWS_VALID | The common views folder has a valid entry identifier
| 0x0080 | FOLDER_FINDER_VALID | The finder folder has a valid entry identifier.
|===

=== [[container_flag_definitions]]Container flag definitions

The container flag definitions are used by the following properties:

* 0x3600 (PidTagContainerFlags)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | AB_RECIPIENTS | The container can hold recipients. This flag does not indicate whether any recipients are actually present in the container, or whether they can be added or removed.
| 0x00000002 | AB_SUBCONTAINERS | The container can hold child containers. This flag does not indicate whether any subcontainers are actually present in the container, nor whether they can be added or removed.
| 0x00000004 | AB_MODIFIABLE | Entries can be added to and removed from the container. This flag does not indicate whether any entries in the container can be modified.
| 0x00000008 | AB_UNMODIFIABLE | Entries cannot be added to or removed from the container. This flag does not indicate whether any entries in the container can be modified.
| 0x00000010 | AB_FIND_ON_OPEN | Displays a dialog box to request a restriction before displaying any contents of the container.
| 0x00000020 | AB_NOT_DEFAULT | The container is not the default one
|===

=== [[folder_type_definitions]]Folder type definitions

The folder type definitions are used by the following properties:

* 0x3601 (PidTagFolderType)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | FOLDER_ROOT | The root folder of the folder hierarchy table, that is, a folder that has no parent folder.
| 1 | FOLDER_GENERIC | A generic folder that contains messages and other folders.
| 2 | FOLDER_SEARCH | A folder that contains the results of a search, in the form of links to messages that meet search criteria.
| | |
| 4 | | [yellow-background]*Unknown (MDB Attachments Folder)* +
Seen in an Exchange database
|===

=== [[aging_granularity_definitions]]Aging granularity definitions

The folder type definitions are used by the following properties:

* 0x36ee (PR_AGING_GRANULARITY)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | AG_MONTHS | 0x36ec (PR_AGING_PERIOD) is defined in months
| 1 | AG_WEEKS | 0x36ec (PR_AGING_PERIOD) is defined in weeks
| 2 | AG_DAYS | 0x36ec (PR_AGING_PERIOD) is defined in days
|===

=== [[attachment_method_definitions]]Attachment method definitions

The attachment method definitions are used by the following properties:

* 0x3705 (PidTagAttachMethod)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | NO_ATTACHMENT | None (No attachment)
| 1 | ATTACH_BY_VALUE | By value +
The PR_ATTACH_DATA_BIN (PidTagAttachDataBinary) property contains the attachment data.
| 2 | ATTACH_BY_REFERENCE | By reference +
The PidTagAttachPathname (PR_ATTACH_PATHNAME) or PidTagAttachLongPathname  (PR_ATTACH_LONG_PATHNAME) property contains a fully-qualified path identifying the attachment to recipients with access to a common file server.
| 3 | ATTACH_BY_REF_RESOLVE | By reference resolve +
The PidTagAttachPathname (PR_ATTACH_PATHNAME) or PidTagAttachLongPathname  (PR_ATTACH_LONG_PATHNAME) property  contains a fully-qualified path identifying the attachment.
| 4 | ATTACH_BY_REF_ONLY | By reference only +
The PidTagAttachPathname (PR_ATTACH_PATHNAME) or PidTagAttachLongPathname  (PR_ATTACH_LONG_PATHNAME) property  contains a fully-qualified path identifying the attachment.
| 5 | ATTACH_EMBEDDED_MSG | Embedded message +
The PidTagAttachDataObject (PR_ATTACH_DATA_OBJ) property contains an embedded object that supports the IMessage interface.
| 6 | ATTACH_OLE | OLE +
The attachment is an embedded OLE object. +
When the OLE object is in OLE 2.0 IStorage format, the data is accessible through PidTagAttachDataObject (PR_ATTACH_DATA_OBJ). When the OLE object is in OLE 1.0 OLESTREAM format, the data is accessible through PR_ATTACH_DATA_BIN as an IStream. The type of the OLE encoding can be determined by the PidTagAttachTag (PR_ATTACH_TAG) value.
|===

=== [[attachment_flag_definitions]]Attachment flag definitions

The attachment flags definitions are used by the following properties:

* 0x3714 (PidTagAttachFlags)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | ATT_INVISIBLE_IN_HTML | Attachment not available in HTML
| 0x00000002 | ATT_INVISIBLE_IN_RTF | Attachment not available in RTF
| 0x00000004 | ATT_MHTML_REF | [yellow-background]*Unknown*
|===

=== [[icon_display_type_definitions]]Icon display type definitions

The icon display type definitions are used by the following properties:

* 0x3900 (PidTagDisplayType)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
3+| _Used by address book contents tables_
| 0x00000000 | DT_MAILUSER | A typical messaging user with a mailbox.
| 0x00000001 | DT_DISTLIST | A distribution list.
| 0x00000002 | DT_FORUM | A forum, such as a bulletin board service or a public or shared folder.
| 0x00000003 | DT_AGENT | A dynamic distribution list or an automated agent, such as Quote-Of-The-Day or a weather chart display.
| 0x00000004 | DT_PRIVATE_DISTLIST | A private, personally administered distribution list.
| 0x00000005 | DT_ORGANIZATION | A special alias defined for a large group, such as helpdesk, accounting, or blood-drive coordinator.
| 0x00000006 | DT_REMOTE_MAILUSER | A recipient known to be from a foreign or remote messaging system or an address list entry in the Global Address List.
| 0x00000007 | DT_ROOM | Conference room.
| 0x00000008 | DT_EQUIPMENT | Equipment, for example, a printer or a projector.
| 0x00000009 | DT_SEC_DISTLIST | Security distribution list.
3+| _Used by address book hierarchy tables and one-off tables_
| 0x00010000 | DT_MODIFIABLE | Modifiable; the container should be denoted as modifiable in the user interface.
| 0x00020000 | DT_GLOBAL | A global address book.
| 0x00030000 | DT_LOCAL | A local address book that you share with a small workgroup.
| 0x00040000 | DT_WAN | A wide area network address book.
| 0x00050000 | DT_NOT_SPECIFIC | Does not match any of the other settings.
3+| _Used by folder hierarchy tables_
| 0x01000000 | DT_FOLDER | Display default folder icon adjacent to folder.
| 0x02000000 | DT_FOLDER_LINK | Display default folder link icon adjacent to folder rather than the default folder icon.
| 0x04000000 | DT_FOLDER_SPECIAL | Display icon for a folder with an application-specific distinction, such as a special type of public folder.
|===

If this property is not set, the client should assume the default type
appropriate for the table, typically DT_FOLDER, DT_LOCAL, or DT_MAILUSER.

=== [[extended_icon_display_type_definitions]]Extended icon display type definitions

The icon display type definitions are used by the following properties:

* 0x3905 (PidTagDisplayTypeEx)

The following are conveniance macro's for the extended icon display type defintions.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x000000ff | DTE_MASK_LOCAL |
| 0x0000ff00 | DTE_MASK_REMOTE |
| 0x40000000 | DTE_FLAG_ACL_CAPABLE |
| 0x80000000 | DTE_FLAG_REMOTE_VALID |
|===

The actual definitions other than the icon display type definitions are currently
not specified.

* [yellow-background]*Per MSDN the client applications must not define any new
values and must be prepared to deal with an undocumented value.*

=== [[gender_definitions]]Gender definitions

The gender definitions are used by the following properties:

* 0x3a4d (PidTagGender)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | genderUnspecified | Unspecified
| 0x0001 | genderFemale | Female
| 0x0002 | genderMale | Male
|===

=== [[encoding_preference_flag_definitions]]Encoding preference flag definitions

The encoding preference flag definitions are used by the following properties:

* 0x3a71 (PidTagSendInternetEncoding)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00010000 | MAPI_SEND_NO_RICH_INFO | [yellow-background]*Unknown*
| 0x00020000 | ENCODING_PREFERENCE | If not set the encoding is left to the messaging system.
| 0x00040000 | ENCODING_MIME | Encode the message using MIME. +
If not set the message body is encoded in plain text and the attachments in UUENCODE.
| 0x00080000 | BODY_ENCODING_HTML | Encode the message body in HTML. +
Ignored unless the ENCODING_MIME is set.
| 0x00100000 | BODY_ENCODING_TEXT_AND_HTML | Encode the message body in text and HTML using Multipurpose Internet Mail Extensions (MIME) multipart alternatives. +
Ignored unless the ENCODING_MIME is set.
| 0x00200000 | MAC_ATTACH_ENCODING_UUENCODE | Encode Macintosh attachments in Apple double mode. +
Ignored unless the ENCODING_MIME is set.
| 0x00400000 | MAC_ATTACH_ENCODING_APPLESINGLE | Encode Macintosh attachments in Apple single mode. +
Ignored unless the ENCODING_MIME is set.
| 0x00600000 | MAC_ATTACH_ENCODING_APPLEDOUBLE | Encode Macintosh attachments in UUENCODE. +
If ENCODING_MIME flag is set, this flag is ignored and BinHex encoding is used.
| | |
| 0x10000000 | OOP_DONT_LOOKUP | [yellow-background]*Unknown*
|===

Note that MAC_ATTACH_ENCODING_APPLEDOUBLE (0x00600000) consists of 2 flags.

=== [[codepage_definitions]]Codepage definitions

* [yellow-background]*TODO: migrate documentation*

=== [[conflict_resolution_method_definitions]]Conflict resolution method definitions

The conflict resolution method definitions are used by the following properties:

* 0x3fe7 (PidTagResolveMethod)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | LVE_METHOD_DEFAULT | Conflict resolve message should be generated.
| 0x00000001 | RESOLVE_METHOD_LAST_WRITER_WINS | Overwrite target message with current changes being applied.
| 0x00000002 | RESOLVE_NO_CONFLICT_NOTIFICATION | Do not send conflict notification message when generating conflict resolve message in public folder.
|===

=== [[message_editor_format_definitions]]Message editor format definitions

The message editor format definitions are used by the following properties:

* 0x5909 (PidTagMessageEditorFormat)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | EDITOR_FORMAT_DONTKNOW | The format for the editor to use is unknown.
| 1 | EDITOR_FORMAT_PLAINTEXT | The editor should display the message in plain text format.
| 2 | EDITOR_FORMAT_HTML | The editor should display the message in HTML format.
| 3 | EDITOR_FORMAT_RTF | The editor should display the message in Rich Text Format.
|===

=== [[rpc_over_http_flag_definitions]]RPC over HTTP flag definitions

The RPC over HTTP flag definitions are used by the following properties:

* 0x6623 (PR_ROH_FLAGS)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | ROHFLAGS_USE_ROH | Connect to the Exchange Server using RPC over HTTP.
| 0x00000002 | ROHFLAGS_SSL_ONLY | Connect to the Exchange Server using Secure Socket Layer (SSL) only.
| 0x00000004 | ROHFLAGS_MUTUAL_AUTH | Mutually authenticate the session when connecting by using SSL.
| 0x00000008 | ROHFLAGS_HTTP_FIRST_ON_FAST | On fast networks, connect by using HTTP first. Then, connect by using TCP/IP.
| | |
| 0x00000020 | ROHFLAGS_HTTP_FIRST_ON_SLOW | On slow networks, connect by using HTTP first. Then, connect by using TCP/IP.
|===

=== [[rpc_over_http_authentication_scheme_definitions]]RPC over HTTP authentication scheme definitions

The RPC over HTTP authentication scheme definitions are used by the following
properties:

* 0x6627 (PR_ROH_PROXY_AUTH_SCHEME)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | ROHAUTH_BASIC | Basic authentication
| 0x00000002 | ROHAUTH_NTLM | NTLM authentication
|===

=== [[personal_storage_table_configuration_flags_definitions]]Personal storage table configuration flags definitions

The personal storage table configuration flags definitions are used by
the following entry types:

* 0x6770 (PidTagPstConfigurationFlags)

[cols="1,1,5",options="header"]
|===
| Bit(s) | Identifier | Description
| 0x00000001 | PST_CONFIG_CREATE_NOWARN | Do not warn if not configured
| 0x00000002 | PST_CONFIG_PRESERVE_DISPLAY_NAME | Preserve display name property
| | |
| 0x00000008 | OST_CONFIG_POLICY_DELAY_IGNORE_OST | Prompt user for location of missing OST file
| 0x00000010 | OST_CONFIG_CREATE_NEW_DEFAULT | Make a new copy of the OST file
| | |
| 0x80000000 | PST_CONFIG_UNICODE | Unicode PST file
|===

=== [[view_class_identifier_definitions]]View class identifier definitions

The view class identifier definitions definitions are used by the following
properties:

* 0x6833 (PR_VIEW_CLSID)

[cols="1,5",options="header"]
|===
| Identifier | Service provider
| [yellow-background]*00062000-0000-0000-c000-000000000046* |
|===

=== [[address_book_provider_type_definitions]]Address book provider type definitions

The address book provider type definitions definitions are used by
the following properties:

* 0x00008029 (PidLidAddressBookProviderArrayType)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | | Email1 is defined for the contact.
| 0x00000002 | | Email2 is defined for the contact.
| 0x00000004 | | Email3 is defined for the contact.
| 0x00000008 | | Business fax is defined for the contact.
| 0x00000010 | | Home fax is defined for the contact.
| 0x00000020 | | Primary fax is defined for the contact.
|===

=== [[appointment_sequence_definitions]]Appointment sequence definitions

The appointment sequence definitions are used by the following properties:

* 0x00008201 (PidLidAppointmentSequence)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | asfMeeting (M) | This flag indicates that the object is a meeting object or a meeting-related object.
| 0x00000002 | asfReceived (R) | This flag indicates that the represented object was received from someone else.
| 0x00000004 | asfCanceled (C) | This flag indicates that the meeting object represented by the object has been canceled.
|===

=== [[appointment_color_definitions]]Appointment color definitions

The appointment color definitions are used by the following properties:

* 0x00008214 (PidLidAppointmentColor)

[cols="1,5",options="header"]
|===
| Value | Description
| 0x00000000 | None
| 0x00000001 | Red
| 0x00000002 | Blue
| 0x00000003 | Green
| 0x00000004 | Grey
| 0x00000005 | Orange
| 0x00000006 | Cyan
| 0x00000007 | Olive
| 0x00000008 | Purple
| 0x00000009 | Teal
| 0x0000000a | Yellow
|===

=== [[side_effect_definitions]]Side effect definitions

The side effect definitions are used by the following properties:

* 0x00008510 (PidLidSideEffects)

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | seOpenToDelete | Additional processing is required on the message object when deleting.
| | |
| 0x00000008 | seNoFrame | No UI is associated with the message object.
| 0x00000010 | seCoerceToInbox | Additional processing is required on the message object when moving or copying to a folder object with a PidTagContainerClass (PR_CONTAINER_CLASS) property of "IPF.Note". +
See section: <<container_class_definitions,Container class definitions>>
| 0x00000020 | seOpenTocopy | Additional processing is required on the message object when copying to another folder.
| 0x00000040 | seOpenToMove | Additional processing is required on the message object when moving to another folder.
| | |
| 0x00000100 | seOpenForCtxMenu | Additional processing is required on the message object when displaying verbs to the end-user.
| | |
| 0x00000400 | seCannotUndoDelete | Cannot undo delete operation, must not be set unless "seOpenToDelete" is set.
| 0x00000800 | seCannotUndoCopy | Cannot undo copy operation, must not be set unless "seOpenTocopy" is set.
| 0x00001000 | seCannotUndoMove | Cannot undo move operation, must not be set unless "seOpenToMove" is set.
| 0x00002000 | seHasScript | The message object contains end-user script.
| 0x00004000 | seOpenToPermDelete | Additional processing is required to permanently delete the message object.
|===

=== [[task_mode_definitions]]Task mode definitions

The task mode definitions are used by the following properties:

* 0x00008518 (PidLidTaskMode)

[cols="1,5",options="header"]
|===
| Value | Description
| 0x00000000 | The task is not assigned.
| 0x00000001 | The task is embedded in a task request.
| 0x00000002 | The task was accepted (by the task assignee).
| 0x00000003 | The task was rejected (by the task assignee).
| 0x00000004 | The task is embedded in a task update.
| 0x00000005 | The task was assigned to the task assigner.
|===

== MAPI data types

=== [[mapi_x400_object_identifiers]]MAPI X.400 object identifiers (MAPIOID)

The MAPI X.400 object identifiers are used by the following properties:

* 0x3702 (PidTagAttachEncoding)
* 0x370a (PidTagAttachTag)

The MAPI X.400 object identifier consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 7 | | The MAPI prefix +
Contains: 0x2a 0x86 0x48 0x86 0xf7 0x14 0x03
| 7 | 1 | | Object identifier type +
0x0a => tag +
0x0b => encoding
| 8 | ... | | Object identifier data +
Known tags (0x0a) +
0x01 => TNEF +
0x03 => OLE +
0x03 0x01 => OLE1 +
0x03 0x01 0x01 => OLE1 storage +
0x03 0x02 => OLE2 +
0x03 0x02 0x01 => OLE2 storage +
0x04 => Mime +
 +
Known encodings (0x0b) +
0x01 => MacBinary
|===

....
References:
initoid.h
mapioid.h

OID 1 0xb0 0xb1
OID 2 0xb0 0xb1 0xb2
OID 3 0xb0 0xb1 0xb2 0xb3
OID 4 0xb0 0xb1 0xb2 0xb3 0xb4

[MSDN]
For complete information on these object identifiers, see the documentation on ASN.1, X.208, and X.209. The object identifier is found in the application-reference element of the FTBP (File Transfer Body Part) environment.
....

....
libpff_table_read_entry_value: table set: 000 entry: 006 item entry type                        : 0x370a (PR_ATTACH_TAG : Attachment application tag)
libpff_table_read_entry_value: table set: 000 entry: 006 item entry value type                  : 0x0102 (PT_BINARY : Binary data)
libpff_table_read_entry_value: table set: 000 entry: 006 item entry value                       : at offset: 211 of size: 9
00000000: 2a 86 48 86 f7 14 03 0a  04                        *.H..... .

found with a MacBinary PR_ATTACH_ENCODING
....

=== The MAPI unique identifier (MAPIUID)

The MAPIUID is a little-endian version of a GUID.

TheMAPIUID is used by the following entry types:

* 0x3414 (PidTagStoreProvider)
* 0x3615 (PidTagAbProviderId)

=== The embedded object

The embedded object has a value type of 0x000d (Embedded object)

The embedded object is used by the following entry types:

* 0x3701 (PidTagAttachDataObject)

The embedded object is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Local descriptor identifier
| 4 | 4 | | [yellow-background]*Unknown*
|===

=== [[entry_identifier_structure]]The entry identifier structure (ENTRYID)

The entry type should be of value type 0x0102 (Binary data). The entry
identifier is used to define object specific references in a generic way.

The entry identifier structure is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Flags +
Contains a byte array
| 4 | 16 | | Service provider identifier +
Contains a  MAPIUID
| 20 | ... | | Object identifier
|===

==== The entry identifier flags

The first byte of the entry identifier flags can contain the following flags:

[cols="1,1,5",options="header"]
|===
| Bit(s) | Identifier | Description
| 0x08 | MAPI_NOTRESERVED | Other users cannot access the entry identifier
| 0x10 | MAPI_NOW | The entry identifier cannot be used at other times
| 0x20 | MAPI_THISSESSION | The entry identifier cannot be used on other sessions.
| 0x40 | MAPI_NOTRECIP | The entry identifier cannot be used as a recipient on a message
| 0x80 | MAPI_SHORTTERM | The entry identifier is short-term. All other values in this byte must be set unless other uses of the entry identifier are enabled.
|===

[yellow-background]*Seen 0xff being used in 0x684e of IPM.Microsoft.WunderBar.Link*

....
Entry identifier from and Exchange database table: Folders, column: N3616
Flags                           : 0xef, 0x00, 0x00, 0x00
Service provider identifier     : 19f83992-c48f-47bf-bada-7aaea4ef8ad9 (Unknown)
Object identifier data:
Descriptor identifier           : 1049576
....

The second byte of the entry identifier flags can contain the following flags:

[cols="1,1,5",options="header"]
|===
| Bit(s) | Identifier | Description
| 0x80 | MAPI_COMPOUND |
|===

==== The service provider identifier

[cols="1,5",options="header"]
|===
| Identifier | Service provider
| a41f2b81-a3be-1910-9d6e-00dd010f5402 | One-off entry identifier
| c840a7dc-42c0-1a10-b4b9-08002b2fe182 | X500 address +
[yellow-background]*Main address book?*
| |
| 4a2f9232-b9d7-4afc-a1d5-9634785b50af | [yellow-background]*Unknown (Folder reference (32-bit))*
| 4b2ef2ba-7cd4-4f00-a536-a91f779c1d42 | [yellow-background]*Unknown (Folder reference (64-bit))*
| 828a5cbd-68fa-49e8-bfab-60c8b4ee1bf6 | [yellow-background]*Unknown (Folder reference (32-bit) (Outlook 2000))*
| 829f38c5-0f8f-48db-942b-2adceac3d50b | [yellow-background]*Unknown (Folder reference (64-bit) (Outlook 2003 11.0))*
| |
| 94e24743-0110-4003-a103-7e01054f2e69 | [yellow-background]*Unknown*
| |
| d3ad91c0-9d51-11cf-a4a9-00aa0047faa4 | Windows address book (WAB) wrapped entry identifier (WAB_GUID)
| |
| f0f35091-7e99-4783-8c97-045ccd019790 | [yellow-background]*Unknown*
|===

==== Object identifiers

===== Folder reference

The folder reference has service provider identifier:

* 4a2f9232-b9d7-4afc-a1d5-9634785b50af
* 4b2ef2ba-7cd4-4f00-a536-a91f779c1d42
* 828a5cbd-68fa-49e8-bfab-60c8b4ee1bf6
* 829f38c5-0f8f-48db-942b-2adceac3d50b

The folder reference entry identifier is used by the following entry types:

* 0x3416
* 0x35e0 (PR_IPM_SUBTREE_ENTRYID)
* 0x35e2 (PR_IPM_OUTBOX_ENTRYID)
* 0x35e3 (PR_IPM_WASTEBASKET_ENTRYID)
* 0x35e4 (PR_IPM_SENTMAIL_ENTRYID)
* 0x35e5 (PR_VIEWS_ENTRYID)
* 0x35e6 (PR_COMMON_VIEWS_ENTRYID)
* 0x35e7 (PR_FINDER_ENTRYID)
* 0x36d0 (PR_IPM_APPOINTMENT_ENTRYID)
* 0x36d1 (PR_IPM_CONTACT_ENTRYID)
* 0x36d3 (PR_IPM_NOTE_ENTRYID)
* 0x36d4 (PR_IPM_TASK_ENTRYID)
* 0x36d5 (PR_REMINDERS_ONLINE_ENTRYID)
* 0x36d7 (PR_IPM_DRAFTS_ENTRYID)

The object identifier is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | (item) descriptor identifier
|===

===== 94e24743-0110-4003-a103-7e01054f2e69

....
Found in 64-bit pst
libpff_table_read_entry_value: table set: 00 entry: 004 item entry type                 : 0x3416 (Folder information reference to "ItemProcSearch")
libpff_table_read_entry_value: table set: 00 entry: 004 item entry value type           : 0x0102 (Binary data)
libpff_table_read_entry_value: table set: 00 entry: 004 item entry value                : at offset: 368 of size: 46
00000000: 00 00 00 00 43 47 e2 94   10 01 03 40 a1 03 7e 01
00000010: 05 4f 2e 69 01 00 38 12   ec 33 e1 a4 38 44 bd 5c
00000020: 54 32 64 30 01 52 00 00   0e 34 00 03 00 00
....

===== One-off entry identifier

The one-off entry identifier has service provider identifier:

* a41f2b81-a3be-1910-9d6e-00dd010f5402

The one-off entry identifier is used by the following entry types:

* 0x003f (PR_RECEIVED_BY_ENTRYID)
* 0x0041 (PR_SENT_REPRESENTING_ENTRYID)
* 0x0043 (PR_RCVD_REPRESENTING_ENTRYID)
* 0x0c19 (PR_SENDER_ENTRYID)
* 0x0e0a (PR_SENTMAIL_ENTRYID)

One-off entry identifiers are used for addresses not found in any available address books.

The object identifier of the one-off entry identifier consists off:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | 0x0000 | Version
| 2 | 2 | | Flags
| 4 | ... | | Display name +
ASCII or Unicode string terminated by end-of-string character
| ... | ... | | Address type +
ASCII or Unicode string terminated by end-of-string character +
See section: <<address_type_definitions,Address type definitions>>
| ... | ... | | E-mail address +
ASCII or Unicode string terminated by end-of-string character
|===

====== One-off entry identifier flags

The one-off entry identifier flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0001 | MAPI_ONE_OFF_NO_RICH_INFO | Set if a recipient should not receive message content in the Transport Neutral Encapsulation Format (TNEF)
| | |
| 0x1000 | | [yellow-background]*Unknown*
| | |
| 0x8000 | MAPI_ONE_OFF_UNICODE | Set if the display name and e-mail address are Unicode strings
|===

===== X500 address

The X500 address has service provider identifier:

* c840a7dc-42c0-1a10-b4b9-08002b2fe182

The X500 address entry identifier is used by the following entry types:

* 0x003f (PR_RECEIVED_BY_ENTRYID)
* 0x0041 (PR_SENT_REPRESENTING_ENTRYID)
* 0x0043 (PR_RCVD_REPRESENTING_ENTRYID)
* 0x0c19 (PR_SENDER_ENTRYID)
* 0x0e0a (PR_SENTMAIL_ENTRYID)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0x00000001 | [yellow-background]*Unknown* +
X500 type indicator?
| 4 | 4 | 0x00000000 +
0x00000001 | [yellow-background]*Unknown*
| 10 | | | X500 address +
ASCII string terminated by end-of-string character
|===

===== Windows address book (WAB) wrapped entry identifier

The Windows address book (WAB) wrapped entry identifier has service provider identifier:

* d3ad91c0-9d51-11cf-a4a9-00aa0047faa4

Notes:

....
Object identifier data:
00000000: c3 00 00 00 00                                     .....f.k ....O.&.

00000000:                66 1d 6b  0b d8 0f eb 4f a6 26 99   .....f.k ....O.&.
00000010: 8f 17 10 df 2f                                     ..../..c q.9.T.E.

00000010:                07 00                               ..../..c q.9.T.E.

00000010:                      63  71 e1 39 15 54 85 45 9f   ..../..c q.9.T.E.
00000020: 77 30 f7 fd 71 c3 84                               w0..q... ....A..c

00000020:                      00  00 00 01 00 41 00 00      w0..q... ....A..c

00000020:                                               63   w0..q... ....A..c
00000030: 71 e1 39 15 54 85 45 9f  77 30 f7 fd 71 c3 84      q.9.T.E. w0..q...

00000030:                                               00   q.9.T.E. w0..q...
00000040: 00 00 02 07 15 00 00                               .......

00000000: 83 00 00 00 00 eb 0b 71  48 23 72 4d 4c ad 56 a1   .......q H#rML.V.
00000010: a5 06 22 32 5b c4 08 2d  00                        .."2[..- .

enum
{
BFLAGS_INTERNAL_MAILUSER		= 0x03,	// Outlook Contact
BFLAGS_INTERNAL_DISTLIST,			// Outlook Distribution List
BFLAGS_EXTERNAL_MAILUSER,			// external (MAPI) Contact
BFLAGS_EXTERNAL_DISTLIST,			// external (MAPI) Distribution List
BFLAGS_MASK_OUTLOOK		= 0x80,	// bit pattern 1000 0000
};
....


=== The entries structure

The entries structure has a value type of 0x0102 (Binary data). It is basically
an array of entry identifiers. The entries structure is used by:

* 0x004f (PR_REPLY_RECIPIENT_ENTRIES)

The entries structure is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 |4 | |The number of entries
| 4 |4 | |The size of the entries
4+| _Entries_
| 8 | 4 | | Entry data size
| 12 | ... | | Entry data +
(consists of an entry identifier structure)
|===

=== The multi value entry identifiers structure

The multi value entry identifiers structure has a value type of 0x1102 (Array
of Binary data values). It is basically an array followed by an entry
identifier. The multi value entry identifiers structure is used by:

* 0x36d8 (PR_ADDITIONAL_REN_ENTRYIDS)
* 0x36e4 (PR_FREEBUSY_ENTRYIDS)

The entries structure is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | The number of entries
4+| _Entries_
| 4 | 4 | | Entry identifier offset +
The offset is relative to the start of the multi value entry identifiers structure and stored after the entries
4+| _Entries data (stored after the entries)_
| ... | [yellow-background]*24* | | Entry data +
(consists of an entry identifier structure)
|===

[yellow-background]*Contains a folder reference entry identifier; is the size
fixed or does it need to be determined run-time?*

=== [[change_key_structure]]The change key structure

The change key structure has a value type of 0x0102 (Binary data) and is used
by:

* 0x65e2 (PR_CHANGE_KEY)

The change list structure consists of a variable size:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 10 | 16 | | [yellow-background]*GUID*
| 16 | ... | | [yellow-background]*Data*
|===

=== [[change_list_structure]] The change list structure

The change list (PredecessorChangeList) structure has a value type of 0x0102
(Binary data) and is used by:

* 0x65e3 (PR_PREDECESSOR_CHANGE_LIST)

The change list structure consists of multiple entries of a variable size:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | [yellow-background]*Size*
| 1 | 16 | | [yellow-background]*GUID*
| 17 | Size – 16 | | [yellow-background]*Data*
|===

[yellow-background]*The first (in PST) and the second (in OST) entry
(GUID + Data) equals the search key*

....
Contains a set of external identifiers (XIDs) (is GUID) that represent change
numbers of messaging objects in different replicas. The order of the XIDs does
not have significance for interpretation, but is significant for serialization
and deserialization. The set of XIDs MUST be serialized without padding as an
array of SizedXid structures binary-sorted by the value of NamespaceGuid field
of the XID structure in the ascending order.
....

=== [[conversation_index_structure]]The conversation index structure

The conversation index structure has a value type of 0x0102 (Binary data). The
conversation index structure is used by:

* 0x0071 (PidTagConversationIndex)

The conversation index structure consists of:

* a header block
* optional child blocks

The header block is 22 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 6 | | Current system time in UTC +
The 6 most significant bytes of a filetime structure in big-endian +
According to [MAPI] the first byte is reserved 0x01, however it makes more sense that the first byte is part of the current system time
| 6 | 16 | | GUID +
[yellow-background]*It is assumed that the GUID is also in big-endian*
|===

The current system time can be converted into a little-endian filetime stream,
in which the lower 32-bit of the filetime are stored first.

....
stream[ 0 ] = 0
stream[ 1 ] = 0
stream[ 2 ] = header_block[ 5 ]
stream[ 3 ] = header_block[ 4 ]
stream[ 4 ] = header_block[ 3 ]
stream[ 5 ] = header_block[ 2 ]
stream[ 6 ] = header_block[ 1 ]
stream[ 7 ] = header_block[ 0 ]
....

The stream needs to be converted into two 32-bit values.

....
filetime.lower = convert_stream_to_32bit( stream[ 0 – 3 ], little_endian )
filetime.upper = convert_stream_to_32bit( stream[ 4 – 7 ], little_endian )
....

The child blocks is 5 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 bit | | The time range bit +
Represents the difference between the current time and the time stored in the header block.
| 0.1 | 31 bits | | Current system time delta +
The difference between the current time and the time in the previous header or child block expressed in filetime units. This value is stored in big-endian. +
[yellow-background]*Note that MSDN refers to this as the difference between the current time and the header block, after looking at the creation time of multiple e-mail messages this does not make sense.*
| 4 | 4 bits | | A random number generated by calling the Win32 function GetTickCount.
| 4.4 | 4 bits | | A sequence count that is taken from part of the random number.
|===

The current system time delta is represented in two different ways. If the
time range bit is:

* not set (0) the difference is less than .02 second and greater than two years. This results in that the high 15 bits and the low 18 bits of the current system time in the header block are discarded.
* set (1) the difference is less than one second and greater than 56 years. This results in that the high 10 bits and the low 23 bits of the current system time in the header block are discarded.

=== The embedded object information reference record

The entry type should be of value type 0x000d (Embedded object)

The Embedded object information reference record consists of 8 bytes:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | The descriptor index identifier
| 4 | 4 | | The object size
|===

=== [[security_desciptor_structure]]The security descriptor structure

The entry type should be of value type 0x0102 (Binary data)

The security descriptor structure is used by the following entry types:

* 0x0e27 (ptagNTSD)
* 0x3d21 (ptagAdminNTSD)

The security descriptor is variable of size and consists of:

* security descriptor transfer header
* NT security descriptor

The security descriptor transfer header is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Byte size of the header
| 2 | 2 | | The version +
[yellow-background]*(SECURITY_DESCRIPTOR_TRANSFER_VERSION)*
| 4 | 4 | | Security information flags
| 8 | ...  | | [yellow-background]*Additional data*
|===

The additional data consists of:

....

//  <0 or more>
//          2 BYTES                                 Property Tag
//          16 BYTES                                Named Property GUID
//          1 BYTE                                  Named property "kind"
//          if (kind == MNID_ID)
//                  4 BYTES                         Named property ID
//          else
//                  <null terminated property name in UNICODE!!!!!>
....

The security descriptor transfer header is followed by the NT security
descriptor which is also used in several other parts of Windows NT, like NTFS.
For more information see `[NTSID]`.

==== Security information flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | OWNER_SECURITY_INFORMATION | The owner identifier of the object is being referenced.
| 0x00000002 | GROUP_SECURITY_INFORMATION | The primary group identifier of the object is being referenced.
| 0x00000004 | DACL_SECURITY_INFORMATION | The DACL of the object is being referenced.
| 0x00000008 | SACL_SECURITY_INFORMATION | The SACL of the object is being referenced.
| 0x00000010 | LABEL_SECURITY_INFORMATION | The mandatory integrity label is being referenced.
| 0x10000000 | PROTECTED_SACL_SECURITY_INFORMATION | The SACL cannot inherit ACEs.
| 0x20000000 | PROTECTED_DACL_SECURITY_INFORMATION | The DACL cannot inherit access control entries (ACEs).
| 0x40000000 | UNPROTECTED_SACL_SECURITY_INFORMATION | The SACL inherits ACEs from the parent object.
| 0x80000000 | UNPROTECTED_DACL_SECURITY_INFORMATION | The DACL inherits ACEs from the parent object.
|===

=== [[persist_data_block_structure]]Persist data block structure

The entry type should be of value type 0x0102 (Binary data)

The persist data block structure is used by the following entry types:

* 0x36d9 (PidTagAdditionalRenEntryIdsEx)

The persist data block structure is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Block type (PersistID)
| 2 | 2 | | Size of elements data (DataElementsSize)
| 4 | ...  | | Array of elements (DataElements)
|===

==== Block type

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | PERSIST_SENTINEL | No more persist data blocks need to be processed.
| | |
| 0x8001 | RSF_PID_RSS_SUBSCRIPTION | Block data contains: RSS Subscriptions folder.
| 0x8002 | RSF_PID_SEND_AND_TRACK | Block data contains: Tracked Mail Processing folder.
| | |
| 0x8004 | RSF_PID_TODO_SEARCH | Block data contains: To-Do Search folder.
| | |
| 0x8006 | RSF_PID_CONV_ACTIONS | Block data contains: Conversation Action Settings folder.
| 0x8007 | RSF_PID_COMBINED_ACTIONS | [yellow-background]*Unknown (reserved)*
| 0x8008 | RSF_PID_SUGGESTED_CONTACTS | Block data contains: Suggested Contacts folder.
| 0x8009 | RSF_PID_CONTACT_SEARCH | Block data contains: Contacts Search folder. +
Used only by Outlook.
| 0x800a | RSF_PID_BUDDYLIST_PDLS | Block data contains: Instant Messaging (IM) Contact Lists folder. +
The referenced folder contains Personal Distribution Lists (PDLs) representing each group within the IM Contact list. +
Used by both Outlook and Exchange.
| 0x800b | RSF_PID_BUDDYLIST_CONTACTS | Block data contains: IM Contacts folder. +
The referenced folder contains the individual contacts referenced by the IM Contact List groups. +
Used by both Outlook and Exchange.
|===

If the persists data block type is not one of the ones defined here, the block
is ignored and processing is continued until either a PERSIST_SENTINEL type is
found or the end of the data is reached.

==== Persist data block element

The persist data block element is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Element type (ElementID)
| 2 | 2 | | Size of element data (ElementDataSize)
| 4 | ...  | | Data
|===

===== Element type

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | ELEMENT_SENTINEL | No more persist data elements need to be processed.
| 0x0001 | RSF_ELID_ENTRYID | Data contains the entry identifier of the folder specified by block. +
See section: <<entry_identifier_structure,The entry identifier structure (ENTRYID)>>
| 0x0002 | RSF_ELID_HEADER | [yellow-background]*The data contains a 32-bit (header) value.* +
[yellow-background]*The meaning of this value is dependent on the block type. Also see: `[MS-OXOSFLD]`.*
|===

=== [[lcid_structure]]The LCID structure

The entry type should be of value type 0x0003 (Integer 32-bit signed)

The LCID structure is used by the following entry types:

* 0x3ff1 (PidTagMessageLocaleId)
* 0x65f1 (PR_RULE_MSG_CONDITION_LCID)

For more information see `[NTLCID]`.

=== The free/busy data structure

The entry type should be of value type 0x0102 (Binary data)

The free/busy data structure is used by the following entry types:

* 0x686c (PR_PERSONAL_FREEBUSY)

[yellow-background]*Item type 0x686c with value type 0x0102*

....
00000000: ef be ad de 40 00 00 00   00 00 01 00 00 00 00 00
00000010: 00 00 00 00 00 00 00 00   08 00 00 00 04 00 00 00
00000020: 00 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00
00000030: 00 30 85 90 7a 93 c8 01   00 f0 4b 09 4c b2 c9 01
....

=== The appointment recur structure

The entry type should be of value type 0x0102 (Binary data)

The appointment recur structure is used by the following entry types:

* 0x8216 (PidLidAppointmentRecur)

[yellow-background]*TODO*

....
00000000: 04 30 04 30 0b 20 01 00  00 00 c0 21 00 00 01 00   .0.0. .. ...!....
00000010: 00 00 00 00 00 00 20 00  00 00 23 20 00 00 0a 00   ...... . ..# ....
00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 60 71   ........ ......`q
00000030: c7 0c df 80 e9 5a 06 30  00 00 08 30 00 00 1c 02   .....Z.0 ...0....
00000040: 00 00 3a 02 00 00 00 00  00 00 00 00 00 00 00 00   ..:..... ........
....

=== The time zone structure

The entry type should be of value type 0x0102 (Binary data)

The time zone structure is used by the following entry types:

* 0x8233 (PidLidTimeZoneStruct)

[yellow-background]*TODO*

....
00000000: c4 ff ff ff 00 00 00 00  c4 ff ff ff 00 00 00 00   ........ ........
00000010: 0a 00 00 00 05 00 03 00  00 00 00 00 00 00 00 00   ........ ........
00000020: 00 00 03 00 00 00 05 00  02 00 00 00 00 00 00 00   ........ ........
....

=== The time zone definitions structure

The entry type should be of value type 0x0102 (Binary data)

The time zone definitions structure is used by the following entry types:

* 0x825e (PidLidAppointmentTimeZoneDefinitionStartDisplay)
* 0x825f (PidLidAppointmentTimeZoneDefinitionEndDisplay)

[yellow-background]*TODO*

....
00000000: 02 01 34 00 02 00 17 00  57 00 2e 00 20 00 45 00   ..4..... W... .E.
00000010: 75 00 72 00 6f 00 70 00  65 00 20 00 53 00 74 00   u.r.o.p. e. .S.t.
00000020: 61 00 6e 00 64 00 61 00  72 00 64 00 20 00 54 00   a.n.d.a. r.d. .T.
00000030: 69 00 6d 00 65 00 01 00  02 01 3e 00 02 00 41 06   i.m.e... ..>...A.
00000040: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 c4 ff   ........ ........
00000050: ff ff 00 00 00 00 c4 ff  ff ff 00 00 0a 00 00 00   ........ ........
00000060: 05 00 03 00 00 00 00 00  00 00 00 00 03 00 00 00   ........ ........
00000070: 05 00 02 00 00 00 00 00  00 00                     ........ ..
....

=== [[extended_folder_flags_structure]]The extended folder flags structure

The entry type should be of value type 0x0102 (Binary data)

The extended folder flags are used by the following entry types:

* 0x36da (PidTagExtendedFolderFlags)
* 0x6848 (PidTagSearchFolderEfpFlags)

From `[MAPI]`:

....
This property is a binary stream that contains encoded sub-properties for the
folder. It is formatted as a series of variable length sub items. The first 8
bits of the sub item is an ID field, which indicates what kind of flag the sub
item represents. The second 8 bits is the number of bytes of data that follow.
....

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Extended flag type
| 1 | 1 | | Extended flag data size
| 2 | ...
|===

Extended flag data

Extended flags types:

[cols="1,1,5",options="header"]
|===
| Value | Name | Remarks
| 0x00 | Invalid | Do not use this value
| 0x01 | ExtendedFlags |
| 0x02 | SearchFolderID | The data field is a 16-byte field. When the application creates a persistent search folder, it must set this field on the folder to the same value as the PR_WB_SF_TAG (PidTagSearchFolderId) binary property on the Search Folder Message.
| 0x03 | SearchFolderTag | Specified in `[MS- OXOSRCH]`
| 0x04 | Reserved |
| 0x05 | ToDoFolderVersion | The data field is a 4-byte field. When the application creates the to-do search folder, it must set the value of this field on the folder to the little-endian integer value of" 0x000c0000":
| 0x06 | Reserved |
|===

Extended flag data of type: ExtendedFlags

[cols="1,5",options="header"]
|===
| Bits | Description
| 0‑1 | Reserved.
| 2 | Set to 0 if the application should show a policy description.
| 3‑5 | Reserved.
| 6‑7 | Controls the display of the number of messages in the folder. +
0x00 – Use the default setting +
0x01 – Use the number of unread messages +
0x02 – Use the total number of messages +
0x03 - Invalid
| 8‑31 | Reserved.
|===

Example:

....
0x36da (PidTagExtendedFolderFlags : Extended folder flags)
0x0102 (PT_BINARY : Binary data)
00000000: 01 04 00 00 10 00

01 => extended flags
04 => 32-bit value
0x00100000 => some unknown flag is set
....

....
01 04 00 00 00 01 (Reminders)
01 04 00 00 10 00 (Deleted Items, Inbox, Outbox, Sent Items, Calendar, Journal, Drafts, Notes, RSS Feeds, Tasks, Renamed by MAE)
01 04 08 00 10 00 (Sync Issues, Conflicts, Local Failures, Server Failures)
01 04 00 00 40 00 05 04  00 00 0c 00 (To-Do Search)
01 04 00 00 40 00 (Tracked Mail Processing)
01 04 00 40 10 00 (Contacts)
01 04 00 80 1e 00 (Junk E-mail)
06 04 02 00 00 00 (IPM_SUBTREE)
....

=== The global identifier structure

The entry type should be of value type [yellow-background]*0x0102 (Binary data)*

The global identifier structure (GID) used by the following entry types:

* [yellow-background]*TODO*

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | Database identifier +
Contains a GUID
| 16 | 6 | | Item object identifier (or global counter)
|===

=== [[message_identifier_structure]]The message identifier structure

The entry type should be of value type 0x0014 (Integer 64-bit signed)

The message identifier structure (MID) used by the following entry types:

* 0x674a (PidTagMid)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Store object identifier (or replica identifier)
| 2 | 6 | | Message object identifier (or global counter)
|===

=== [[folder_identifier_structure]]The folder identifier structure

The entry type should be of value type 0x0014 (Integer 64-bit signed)

The folder identifier structure (FID) used by the following entry types:

* 0x6748 (PidTagFolderId)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Store object identifier (or replica identifier)
| 2 | 6 | | Folder object identifier (or global counter)
|===

=== [[folder_web_view_information_structure]]The folder web view information structure

[yellow-background]*TODO*

....
The following is a parse of the sample data for the WebViewPersistenceObject stream.

dwVersion
    Offset 0x0, 4 bytes: 0x00000002 (WEBVIEW_PERSISTENCE_VERSION).

dwType
    Offset 0x4, 4 bytes: 0x00000001 (WEBVIEWURL).

dwFlags
    Offset 0x8, 4 bytes: 0x00000001 (WEBVIEW_FLAGS_SHOWBYDEFAULT).

dwUnused[7]
    Offset 0xC, 28 bytes: all zeros.

cbData
    Offset 0x28, 4 bytes: 0x00000032.

wzURL
    Offset 0x2C, 0x32 bytes: array of 25 WCHARs. A Unicode zero-terminated string value: "http://www.microsoft.com".
....

=== Other structures

==== The 0x6835 (binary view data) structure

The entry type should be of value type 0x0102 (Binary data)

The 0x6835 (binary view data) structure is used by the following entry types:

* 0x6835 (binary view data)

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Signature* +
0xda 0xda 0x00 0x00
| 4 | 4 | | [yellow-background]*Empty*
| 8 | 4 | | [yellow-background]*Unknown* +
0x5c 0xed 0x01 0x00 +
0x6c 0xed 0x01 0x00
| 12 | 4 | | [yellow-background]*Unknown* +
0x33 0x0c 0x00 0x00
| 16 | 4 | | [yellow-background]*Unknown* +
0x80 0x80 0x80 0x00
| 20 | 4 | | [yellow-background]*Unknown* +
0x03 0x00 0x00 0x00
| 24 | 4 | | [yellow-background]*Unknown* +
0x08 0x00 0x00 0x00
| 28 | 4 | | Size of the collapse state
| 32 | ... | | Collapse state data
|===

Examples of the collapse state data

....
00000020: 52 4d 4a 47 02 00 00 00  44 63 30 00 ff ff 02 00   RMJG.... Dc0.....
00000030: 03 00 00 00 01 00 00 00  01 00 00 00 03 00 90 10   ........ ........
00000040: 00 00 00 00 03 00 95 10  00 00 00 00 40 00 06 0e   ........ ....@...
00000050: 01 00 00 00 44 63 30 00  24 d1 2e 00 01 01         ....Dc0. $.....
....

....
00000020: 41 67 67 54 61 62 53 74  61 74 65 00 0c 00 00 00   AggTabSt ate.....
00000030: 01 00 00 00 01 00 00 00  0c 00 00 00 01 00 00 00   ........ ........
00000040: 01 00 00 00 00 00 00 00                            ........
....

Font related data [yellow-background]*(related to the 0x80 0x80 0x80 0x00 value?)*

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | [yellow-background]*Size of the following string in little-endian*
| 2 | 8 | "Segoe UI" | [yellow-background]*Unknown (Name of font)* +
| 10 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x50 0x00*
| 12 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x20 0x00*
| 14 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x40 0x00*
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 2 | | [yellow-background]*Size of the following string in little-endian*
| 22 | 8 | "Segoe UI" | [yellow-background]*Unknown (Name of font)*
| 30 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x50 0x00*
| 32 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x20 0x00*
| 34 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x40 0x00*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 2 | | [yellow-background]*Size of the following string in little-endian*
| 42 | 8 | "Segoe UI" | [yellow-background]*Unknown (Name of font)*
| 50 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x50 0x00*
| 52 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x20 0x00*
| 54 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x40 0x00*
| 56 | 4 | | [yellow-background]*Unknown*
| 60 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*0x10 0x00 0x00 0x00*
| 64 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*0x58 0x00 0x00 0x00*
| 68 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*0xf4 0x01 0x00 0x00*
| 72 | 12 | | [yellow-background]*Empty*
| 84 | 4 | | Number of visible columns
| 88 | ( amount x 4 ) | | Visible column order +
Contains the column index number
| ... | 4 | | Number of column definitions
| ... | ... | | Column definition entries
|===

Column definition entry

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown* +
0x06 0x1f 0x00 0x00 +
0x09 0x1f 0x00 0x00 +
0x11 0x0a 0x40 0x08
| 4 | 4 | | [yellow-background]*Unknown* +
0x80 0x04 0x03 0x00 +
0x80 0x02 0x00 0x00 +
| 0x00 0x01 0x00 0x00
| 8 | 4 | | [yellow-background]*Unknown* +
0x00 0x06 0x00 0x00 +
0x00 0x09 0x00 0x00 +
0x00 0x11 0x00 0x00 +
Relates to value at offset 0
| 12 | 2 | | [yellow-background]*Unknown* +
0x00 0x00
| 14 | 2 | | Property value type
| 15 | 1 | | [yellow-background]*Unknown* +
0x00 => empty +
0x02 => Class identifier
| 16 | ... | | [yellow-background]*Data after previous unknown*
| ... | 1 | | [yellow-background]*Unknown* +
0x00 => empty +
0x01 => 2 byte number of characters + UTF-16 string
| ... | ... | | [yellow-background]*Data after previous unknown*
| ... | 2 | | Property entry type
| ... | 2 | | [yellow-background]*Unknown* +
0x00 0x00
| | 1 | | [yellow-background]*Unknown* +
0x00 => empty +
0x02 => 20 bytes data ? +
0x03 => 7 bytes data? +
0x04 => 4 bytes data +
0x06 => +
| | ... | | [yellow-background]*Data after previous unknown*
| | 1 | | [yellow-background]*Unknown* +
0x00 => empty +
0x0b => 14 bytes data ? +
0x0e => 7 bytes data ?
| | ... | | [yellow-background]*Data after previous unknown*
| ... | 1 | | [yellow-background]*Unknown* +
0x00 => empty
| ... | ... | | [yellow-background]*Data after previous unknown*
| ... | 1 | | [yellow-background]*Unknown* +
0x00 => empty +
0x01 => byte
| ... | ... | | [yellow-background]*Data after previous unknown*
| ... | 4 | | [yellow-background]*Unknown* +
0x00 0x00 0x00 0x00
| ... | 2 | | Narrow heading string length in big-endian
| ... | ... | | Narrow heading string +
ASCII string not NUL-terminated
| ... | 2 | | [yellow-background]*Unknown* +
0x64 0x00
| ... | 2 | | [yellow-background]*Unknown* +
0x02 0x00
| ... | 2 | | [yellow-background]*Unknown* +
0x00 0x00
| ... | 2 | | Text alignment +
0x49 0x01 align left +
0x6a 0x01 align center
| ... | 2 | | [yellow-background]*Unknown* +
0x00 0x00
| ... | 2 | | Column width
| ... | 4 | | Column index number in big-endian +
0x00fe (not used column?)
| ... | 1 | | [yellow-background]*Unknown* +
0x00 +
0xff (not used column?)
| ... | 1 | | [yellow-background]*Unknown* +
0x01 +
0x02
| ... | 4 | | Wide heading string byte size
| ... | 2 | | Wide heading string length in big-endian +
byte size = length x 2
| ... | ...  | | Wide heading string +
UTF-16 string NUL-terminated
| ... | 2 | | [yellow-background]*Unknown* +
[yellow-background]*0x00 0x00*
|===

==== The 0x859c (PidLidSpamOriginalFolder) structure

The entry type should be of value type 0x0102 (Binary data)

The 0x859c (PidLidSpamOriginalFolder) structure is used by the following entry
types:

* 0x859c (PidLidSpamOriginalFolder)

The 00x859c (PidLidSpamOriginalFolder) structure consists of multiple entries
of a variable size:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Empty*
| 4 | 16 | | [yellow-background]*GUID*
| 20 | 2 | | [yellow-background]*Unknown* +
01 00
| 22 | 16 | | [yellow-background]*GUID*
| 38 | 4 | | [yellow-background]*Empty*
| 42 | 4 | | [yellow-background]*Unknown*
|===

== MAPI data

=== [[message_body]]The message body

Both the plain text message body (PidTagBody) and the HTML message body
(PidTagBodyHtml) are stored using a codepage. The codepage (character set) used
can determined as following:

1. use the PidTagInternetCodepage if available
2. else use the PidTagMessageCodepage if available
3. else use the system codepage.

Note that some items do contain both a PidTagInternetCodepage and
PidTagMessageCodepage, but the PidTagMessageCodepage is used to code the plain
text message body (PidTagBody).

== Item classes

The item classes are defined by the MAPI interface definitions:

[cols="1,1,5",options="header"]
|===
| Item class | Corresponding MAPI interface | Parent MAPI interface
| | IMAPIProp | (IUnknown)
| Container | IMAPIContainer | IMAPIProp
| Folder | IMAPIFolder | IMAPIContainer
| Message | IMessage | IMAPIProp
| Message store | IMsgStore | IMAPIProp
| Address book folder | IABContainer | IMAPIContainer
| Attachment | IAttach | IMAPIProp
| Distribution list | IDistList | IMAPIContainer
| Task | |
| Appointment | |
| Contact | |
|===

IUnknown is not a MAPI interface, but actually a COM interface that specifies
the most basic of interfaces. IMAPIProp is the most basic MAPI interface.

=== [[object_type]]Object type

MAPI items sometimes define 0x0ffe PidTagObjectType (PR_OBJECT_TYPE). This
value contains the following values.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | MAPI_STORE | Message store
| 0x00000002 | MAPI_ADDRBOOK | Address book
| 0x00000003 | MAPI_FOLDER | Folder
| 0x00000004 | MAPI_ABCONT | Address book container
| 0x00000005 | MAPI_MESSAGE | Message
| 0x00000006 | MAPI_MAILUSER | (Individual) Recipient
| 0x00000007 | MAPI_ATTACH | Attachment
| 0x00000008 | MAPI_DISTLIST | Distribution list (recipient)
| 0x00000009 | MAPI_PROFSECT | Profile section
| 0x0000000a | MAPI_STATUS | Status object
| 0x0000000b | MAPI_SESSION | Session
| 0x0000000c | MAPI_FORMINFO | Form information
|===

=== [[container_class_definitions]]Container class definitions

The container classes are defined by PidTagContainerClass (PR_CONTAINER_CLASS).
The following are known:

[cols="1,5",options="header"]
|===
| Message type | Usage
| IPF | (inter-personal folder)
| IPF.Note | Folder containing e-mails
| IPF.Appointment | Folder containing appointments
| IPF.Contact | Folder containing contacts
| IPF.Journal | Folder containing journal entries (activities)
| IPF.StickyNote | Folder containing notes
| IPF.Task | Folder containing tasks
| Outlook.ItemProcessor |
| IPF.Note.OutlookHomepage | (used by RSS Feeds folder)
|===

=== [[message_class_definitions]]Message class definitions

Message classes are defined by PidTagMessageClass (PR_MESSAGE_CLASS). The IPM
prefix stands for inter-personal message and is used for most of the visible
items used in Microsoft Outlook. The message class can have a prefix like REPORT
and a suffix like NDR. The middle portion of the message class describes the
item type.

[cols="1,5",options="header"]
|===
| Item type | Usage
| IPM | Common (inter-personal message) +
Items for which the specified form cannot be found
| IPM.Activity | Journal entry
| IPM.Appointment | Appointment
| IPM.Configuration.* | [yellow-background]*Configuration*
| IPM.Conflict.Message | Conflict message
| IPM.Contact | Contact
| IPM.DistList | Distribution list
| IPM.Document.* | Document
| IPM.OLE.Class | [yellow-background]*The exception item of a recurrence series*
| IPM.OLE.CLASS.{00061055-0000-0000-C000-000000000046} | Recurring appointment
| IPM.Note | E-mail message (note)
| IPM.FAX +
IPM.Note.Fax | Fax
| IPM.Note.IMC.Notification | Reports from the Internet Mail Connect (the Exchange Server gateway to the Internet)
| IPM.Note.Mobile.SMS | Mobile text message
| IPM.Note.Mobile.MMS | Mobile multimedia message
| IPM.Note.Rules.OofTemplate.Microsoft | Out-of-office template
| IPM.Note.Secure | Encrypted notes to other people
| IPM.Note.Secure.Sign | Digitally signed notes to other people
| IPM.Note.SMIME | S/MIME e-mail
| IPM.Note.SMIME.MultipartSigned | S/MIME e-mail
| IPM.Note.Voicemail | Voicemail
| IPM.Post | Posting note in a folder
| IPM.Post.RSS | RSS feed
| IPM.Report | Reporting item status
| IPM.Sharing +
IPM.Sharing.* | [yellow-background]*Sharing*
| IPM.Schedule.Meeting.Request | Request for meeting
| IPM.Schedule.Meeting.Resp.* | Response on request for meeting
| IPM.Schedule.Meeting.Canceled | Meeting cancellation
| IPM.Schedule.Meeting.Notification | Notification for meeting
| IPM.StickyNote | Sticky note +
[yellow-background]*MSDN: Creating note*
| IPM.Task | Task
| IPM.TaskRequest.* | Task request
|===

[cols="1,5",options="header"]
|===
| Prefix | Usage
| REPORT | Report +
According to the Exchange protocol documentation REPORT is only used with IPM.Note
|===

[cols="1,5",options="header"]
|===
| Suffix | Usage
2+| REPORT.IPM.Note.*
| REPORT.IPM.Note.DR | Delivery report +
The e-mail was delivered
| REPORT.IPM.Note.NDR | Nondelivery report +
The e-mail could not be delivered
| REPORT.IPM.Note.IPNRN | Read receipt +
The recipient read the e-mail
| REPORT.IPM.Note.IPNNRN | Non-read receipt +
The recipient deleted the e-mail without reading
2+| IPM.Schedule.Meeting.Resp.*
| IPM.Schedule.Meeting.Resp.Neg | Responses to decline meeting requests
| IPM.Schedule.Meeting.Resp.Pos | Responses to accept meeting requests
| IPM.Schedule.Meeting.Resp.Tent | A new time for the meeting is proposed +
[yellow-background]*MSDN: Responses to tentatively accept meeting requests*
2+| REPORT.IPM.Schedule.Meeting.Resp.*
| [yellow-background]*REPORT.IPM.Schedule.Meeting.Request.NDR* |
2+| IPM.TaskRequest.*
| IPM.TaskRequest.Accept | Responses to accept task requests
| IPM.TaskRequest.Decline | Responses to decline task requests
| IPM.TaskRequest.Update | Update for a task requested
2+| IPM.Document.*
| |
|===

==== Notes

Other message classes:

[cols="1,5",options="header"]
|===
| Item type | Usage
| IPM.Microsoft.ScheduleData.FreeBusy | Free Busy Schedule Data
| IPM.Microsoft.FolderDesign.NamedView |
| IPM.Microsoft.WunderBar.Persistence |
| IPM.Microsoft.WunderBar.SFInfo |
| IPM.Microsoft.WunderBar.Link |
| IPM.Microsoft.MigrationStatus |
| |
| IPC.MS.Outlook.AgingProperties |
| |
| IPC.MS.REN.USERFIELDS | Is used for message delivery/read notice?
| |
| IPM.ContactLinkingViews |
| IPM.Contact.OlTrans | (some kind of contact class)
| |
| IPM.MessageManager |
| |
| IPM.Note.StorageQuotaWarning | Storage quota warning
| |
| IPM.Rule.Message |
| IPM.RuleOrganizer | Outlook Rules Organizer
| IPM.Schedule.Meeting | Meeting
| IPM.ExtendedRule.Message |
| |
| IPM.Configuration.Calendar |
| IPM.Configuration.AvailabilityOptions |
| IPM.Configuration.WorkHours |
| IPM.Configuration.RssRule |
| IPM.Configuration.HomeTimeZone |
| IPM.Configuration.CategoryList |
| |
| IPM.ContactLinkingViews |
| IPM.Contact.OlTrans | Contact
| |
| IPM.Note.StorageQuotaWarning |
| |
| IPM.Microsoft.SniffData |
|===
....
IPC
REPORT.IPM

MSDN:
IPM.Recall.Report 	Message recall reports
IPM.Outlook.Recall 	Recalling sent messages from recipient Inboxes
IPM.Remote 	Remote Mail message headers
IPM.Note.Rules.ReplyTemplate.Microsoft 	Editing rule reply templates
IPM.Resend 	Resending a failed message
....

== Other item classes

=== Name to identifier map

[cols="1,1,1,5",options="header"]
|===
| Item | Value | Identifier | Description
| 0x0001 | 0x0003 (Integer 32-bit signed) | PidTagNameidBucketCount | Name-to-ID Map Number of Validation Entries +
[yellow-background]*(Hash bucket count)*
| 0x0002 | 0x0102 (Binary data) | PidTagNameidStreamGuid | Name-to-ID map Class Identifiers +
Contains the name-to-id map table class identifiers
| 0x0003 | 0x0102 (Binary data) | PidTagNameidStreamEntry | Name-to-ID map Entries +
Contains the name-to-id map table entries
| 0x0004 | 0x0102 (Binary data) | PidTagNameidStreamString | Name-to-ID map Strings +
Contains the name-to-id map table strings
| 0x1000 - 0xfffe | 0x0102 (Binary data) | PidTagNameidBucketBase | Name-to-ID Map Validation Entries +
[yellow-background]*(Hash buckets)* +
According to `[MS-PST]` a hash bucket can hold up to 8 validation entries
|===

== [[error_values]]Error values (SCODE)

Error values are stored in a SCODE structure. The SCODE structure is also known
as HRESULT.

The SCODE structure consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 (LSB) | 16 bits | | The error or warning code
| 2 | 11 bits | | Error facility
| 3.3 | 1 bit | | r-bit (Reserved)
| 3.4 | 1 bit | | N-bit (Reserved)
| 3.5 | 1 bit | | C-bit (Reserved)
| 3.6 | 1 bit | | R-bit (Reserved)
| 3.7 | 1 bit | | S-bit (success-bit) +
0 indicates success and 1 failure.
|===

=== Error facility definitions

The SCODE specifies error and warning values for different facilities:

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x000 | FACILITY_NULL | Used for broadly applicable common status codes such as S_OK or E_OUTOF_MEMORY.
| 0x001 | FACILITY_RPC | For status codes returned from remote procedure calls.
| 0x002 | FACILITY_DISPATCH | For late binding IDispatch interface errors.
| 0x003 | FACILITY_STORAGE | For status codes returned from IStorage or IStream method calls relating to structured storage. Status codes with code (lower 16 bits) values in the range of Windows error codes (that is, less than 256) have the same meaning as the corresponding Windows errors.
| 0x004 | FACILITY_ITF | For most status codes returned from interface methods; the value is defined by the interface. That is, two HRESULT values with exactly the same 32-bit value returned from two different interfaces might have different meanings.
3+|
| 0x008 | FACILITY_WINDOWS |
3+|
| 0x010 | FACILITY_SCARD |
| 0x011 | FACILITY_COMPLUS |
3+|
| 0x019 | FACILITY_HTTP |
| 0x020 | FACILITY_BACKGROUNDCOPY |
3+|
| 0x026 | FACILITY_GRAPHICS |
| 0x027 | FACILITY_NAP FACILITY_SHELL |
| 0x028 | FACILITY_INK |
3+|
| 0x030 | FACILITY_PLA |
| 0x031 | FACILITY_FVE |
| 0x032 | FACILITY_FWP |
3+|
| 0x034 | FACILITY_NDIS |
3+|
| 0x7ff | FACILITY_BACKUP |
| 0x800 | FACILITY_NTDSB |
|===

=== Error values

* [yellow-background]*TODO: complete documentation*

== Notes

....
Where is PidTagConversationTracking (Boolean) ?
Where is PidTagConversationId (Binary Data) ?
....

=== Conversation identifier

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | [yellow-background]*Unknown (i)*
| 2 | 4 | | Buffer
| 6 | 64 | | [yellow-background]*Unknown (in)* +
GUID
| 70 | 16 | | MD5 digest hash
|===

=== [[subject_control_codes]]Subject control codes

The PidTagSubject sometimes contains 2 control code character values at the
start of the string.

....
0x01 0x01
0x01 0x04  IPM.Note, ?
0x01 0x05 (RE:)
0x01 0x06  IPM.Note, ?
0x01 0x07  REPORT.IPM.Note.IPNRN, Read Receipt
0x01 0x10  REPORT.IPM.Note.NDR, Undeliverable
0x01 0x14  REPORT.IPM.Note.NDR, Undeliverable
0x01 0x1a  IPM.Note.Rules.OofTemplate.Microsoft, Out of Office AutoReply
....

=== IExchangeModifyTable

[cols="1,5",options="header"]
|===
| MAPI property | Usage
| PR_RULE_ACTIONS | (Defined by MAPI)
| PR_RULE_CONDITION | (Defined by MAPI)
| PR_RULE_ID | (Defined by MAPI)
| PR_RULE_LEVEL | (Defined by MAPI)
| PR_RULE_NAME | (Defined by MAPI)
| PR_RULE_PROVIDER | (Defined by MAPI)
| PR_RULE_PROVIDER_DATA | (Defined by MAPI)
| PR_RULE_SEQUENCE | (Defined by MAPI)
| PR_RULE_STATE | (Defined by MAPI)
| PR_RULE_USER_FLAGS | (Defined by MAPI)
| PR_MEMBER_ENTRYID | (Defined by MAPI)
| PR_MEMBER_ID | (Defined by MAPI)
| PR_MEMBER_NAME | (Defined by MAPI)
| PR_MEMBER_RIGHTS | (Defined by MAPI)
|===

=== IMailUser

[cols="1,5",options="header"]
|===
| MAPI property | Usage
| PR_ADDRTYPE | (Defined by MAPI)
| PR_DISPLAY_NAME | (Defined by MAPI)
| PR_DISPLAY_TYPE | (Defined by MAPI)
| PR_EMAIL_ADDRESS | (Defined by MAPI)
| PR_ENTRYID | (Defined by MAPI)
| PR_OBJECT_TYPE | (Defined by MAPI)
| PR_RECORD_KEY | (Defined by MAPI)
| PR_SEARCH_KEY | (Defined by MAPI)
| PR_ACCOUNT | (Defined by MAPI)
| PR_ASSISTANT | (Defined by MAPI)
| PR_BUSINESS_TELEPHONE_NUMBER | (Defined by MAPI)
| PR_GIVEN_NAME | (Defined by MAPI)
| PR_GOVERNMENT_ID_NUMBER | (Defined by MAPI)
| PR_LOCALITY | (Defined by MAPI)
| PR_POSTAL_ADDRESS | (Defined by MAPI)
|===

=== IMAPIStatus

[cols="1,5",options="header"]
|===
| MAPI property | Usage
| PR_DISPLAY_NAME | (Defined by MAPI)
| PR_PROVIDER_DISPLAY | (Defined by MAPI)
| PR_PROVIDER_DLL_NAME | (Defined by MAPI)
| PR_RESOURCE_FLAGS | (Defined by MAPI)
| PR_RESOURCE_METHODS | (Defined by MAPI)
| PR_RESOURCE_TYPE | (Defined by MAPI)
| PR_STATUS_CODE | (Defined by MAPI)
|===

==== IProfSect

[cols="1,5",options="header"]
|===
| MAPI property | Usage
| PR_OBJECT_TYPE | (Defined by MAPI)
| PR_PROFILE_NAME | (Defined by MAPI)
|===

=== COM class identifiers

[cols="1,5",options="header"]
|===
| Class identifier | Interface
| 00000000-0000-0000-c000-000000000046 | IUnknown
| 00020400-0000-0000-c000-000000000046 | IDispatch
|===

=== The free/busy entry identifiers structure

The entry type should be of value type 0x0102 (Binary data)

The free/busy entry identifiers structure is used by the following entry types:

* 0x36e4 (PR_FREEBUSY_ENTRYIDS)

[yellow-background]*Item type 0x36e4 with value type 0x0102*

....
00000000: 03 00 00 00 10 00 00 00   28 00 00 00 28 00 00 00
Array of 3 values followed by a folder information reference ?
00000010: 00 00 00 00 c5 38 9f 82   8f 0f db 48 94 2b 2a dc
00000020: ea c3 d5 0b 28 00 10 00
Refers to "IPM.Microsoft.ScheduleData.FreeBusy"
....

The value type should be 0x1102

=== Recipient types

....
#define MAPI_P1     0x10000000  /* Recipient is a P1 resend recipient       */
#define MAPI_SUBMITTED 0x80000000 /* Recipient is already processed         */
/* #define MAPI_AUTHORIZE 4        recipient is a CMC authorizing user      */
/*#define MAPI_DISCRETE 0x10000000 Recipient is a P1 resend recipient       */
....

=== PRQ_ID_SECURE4

....
0x0000004400000000 => SPAM Search Folder 2

0x0100000000000000 => IPM_SUBTREE
0x0200000000000000 => NON_IPM_SUBTREE
0x0300000000000000 => EFORMS REGISTRY
0x0400000000000000 => Organization Forms
0x0500000000000000 => Private root folder
0x0600000000000000 => Common Views
0x0700000000000000 => Finder
0x0800000000000000 => Shortcuts
0x0900000000000000 => Views
0x0a00000000000000 => IPM_SUBTREE
0x0f00000000000000 => ~MAPISP(Internal)

0x1000000000000000 => Drizzle
0x1200000000000000 => Shared Data
....

=== Unknown long property identifier (libpst)?

[cols="1,1,1,5",options="header"]
|===
| Item type | Value type | Identifier | Description
| 0xffffffff | 0x101e +
0x101f | | [yellow-background]*Unknown* +
Array of ASCII or Unicode string value
|===

=== FILETIME precision

An estimation of the significance of the bits in the FILETIME (PT_SYSTIME) structure.

[cols="1,5",options="header"]
|===
| Bits | Usage
2+| Lower 32-bit
| 0 – 24 | Mainly significant for the 100ns intervals
| 25 – 29 | Mainly significant for the seconds
| 30 – 31 | Mainly significant for the minutes
2+| Upper 32-bit
| 32 – 35 | Mainly significant for the minutes
| 36 – 40 | Mainly significant for the hours
| 41 – 63 | Mainly significant for the days
|===

=== PR_ATTACH_VIRUS_SCAN_INFO

Found in EDB does not change often

....
03 00 43 41 49 5f 56 00  00 00 00 68 69 80 00 00
00 00 00
....

=== PR_INTERNET_MESSAGE_INFO

Found in EDB does not change often

....
49 4e 46 4f 0a 00 00 00  04 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00  00 00 00 00
....

=== PR_INTERNET_PARSE_STATE

Found in EDB, start of data changes

....
01 00 f2 bd 00 00 00 00  94 00 00 00 f2 bd 00 00
01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00  94 00 00 00 94 00 00 00
00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
....

=== PR_INTERNET_CONTENT

Found in EDB,

....
D0 01 00 00 00 00 00 00  01 00 00 00 00 00 00 00
01 00 00 00 00 00 00 00  00 10 00 00 00 00 00 00
00 20 00 00 00 00 00 00  00 00 00 00 00 00 00 00
....

=== 0x67b2 0x0102

....
03 00 79 0e (0x0e79 0x0003) PR_TRUST_SENDER
03 00 a1 66
03 00 f1 3f
02 01 20 67
03 01 59 66
02 01 c6 66
03 00 fd 3f
03 00 de 3f
02 01 c7 66
0b 00 5a 66
b0 84 55 80
b0 84 42 80
0b 00 47 80
b0 84 41 80
0b 00 46 80
0b 00 48 80
0b 00 49 80
0b 00 4a 80
0b 00 4c 80
48 10 1d 82
0b 00 1f 0e
40 00 39 00
....

=== 0x677f 0x0102

MAPI identifiers

....
14 00 48 67
14 00 88 3f
02 01 b0 67
40 00 8f 66
03 00 43 67 40 00 39 00 14 00 a4 67 02 01 a5 67
14 10 a6 67 02 01 e0 65 02 01 e2 65 02 01 e3 65
02 00 a9 67 0b 00 ad 67 03 00 07 0e 0b 00 aa 67
0b 00 1b 0e 03 00 17 0e 03 00 ab 67 40 00 06 0e
b0 84 1a 00 b0 84 3d 00 b0 84 1d 0e 03 00 17 00
0b 00 ae 67 0b 00 af 67 0b 00 57 00 0b 00 58 00
0b 00 59 00 0b 00 ea 3f 40 00 48 00 02 01 47 00
40 00 07 30 40 00 08 30 0b 00 01 0e fb 00 40 67
02 01 45 67 14 00 4a 67 14 00 80 3f 02 01 c2 65
02 01 f3 3f 02 01 f4 3f 02 01 d4 3f 03 00 23 0e
b0 84 35 10 b0 84 39 10 02 01 68 40 02 01 69 40
b0 84 36 10 02 01 12 10 14 00 4b 67 02 00 f2 65
03 00 f3 65 03 00 e9 65 02 01 f0 65 03 00 f1 65
0b 00 53 67 0b 00 08 67 03 00 00 66 03 00 01 66
03 00 02 66 03 00 03 66 03 00 04 66 b0 84 f3 10
03 00 10 67 b0 84 07 67 40 00 54 66 0b 00 f4 10
0b 00 f5 10 0b 00 f6 10 40 00 09 67 48 10 0c 67
03 00 61 0e 0b 00 62 0e 03 00 08 0e 02 01 b9 67
02 01 ba 67 02 01 bd 67 02 01 be 67
....

=== PR_CONTENTS_SYNCHRONIZER

Flags used by Exchange Incremental Change Synchronization Interface

....
#define SYNC_UNICODE                         0x01
#define SYNC_NO_DELETIONS                    0x02
#define SYNC_NO_SOFT_DELETIONS                   0x04
#define SYNC_READ_STATE                      0x08
#define SYNC_ASSOCIATED                      0x10
#define SYNC_NORMAL                          0x20
#define SYNC_NO_CONFLICTS                    0x40
#define SYNC_ONLY_SPECIFIED_PROPS            0x80
#define SYNC_NO_FOREIGN_KEYS                 0x100
#define SYNC_LIMITED_IMESSAGE                0x200
#define SYNC_CATCHUP                         0x400
#define SYNC_NEW_MESSAGE                     0x800 // only applicable to ImportMessageChange()
#define SYNC_MSG_SELECTIVE                   0x1000 // Used internally. Will reject if used by clients.
#define SYNC_BEST_BODY                       0x2000
#define SYNC_IGNORE_SPECIFIED_ON_ASSOCIATED  0x4000
#define SYNC_PROGRESS_MODE                   0x8000 // AirMapi progress mode
#define SYNC_FXRECOVERMODE                   0x10000
#define SYNC_DEFER_CONFIG                    0x20000
#define SYNC_FORCE_UNICODE                   0x40000 // Forces server to return Unicode properties
....

....
#define CONVENIENT_DEPTH  ((ULONG) 0x00000001
#define SHOW_SOFT_DELETES ((ULONG) 0x00000002)
#define SHOW_SUBFOLDERS   ((ULONG 0x00000004)
....

=== PR_FOLDER_XVIEWINFO_E

....
00000000: 00 00 00 00 4c 02 e1 00  4d 00 65 00 73 00 73 00   ....L... M.e.s.s.
00000010: 61 00 67 00 65 00 73 00  00 00                     a.g.e.s. ..
....

Contains a version number, some flags and a view name in Unicode, all of which
are Outlook specific.

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Version?
| 4 | 4 | | Flags?
| 8 | ... | | View name +
Contains an UTF-16 little-endian string with an end-of-string character.
|===

:numbered!:
[appendix]
== References

`[SMITH02]`

[cols="1,5",options="header"]
|===
| Title: | outlook.pst -- format of MS Outlook .pst file
| Author(s): | David Smith, Joe Nahmias, Brad Hards, Carl Byington
| URL: | https://www.five-ten-sg.com/libpst/rn01re05.html
|===

`[RUSSON]`

[cols="1,5",options="header"]
|===
| Title: | NTFS Documentation
| Author(s): | Richard Russon, Yuval Flede
| URL: | https://dubeyko.com/development/FileSystems/NTFS/ntfsdoc.pdf
|===

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title: | Microsoft Developer Network
| URL: | http://msdn.microsoft.com/
|===

`[MS-OXCFXICS]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-OXCFXICS]`: Bulk Data Transfer Protocol Specification
| URL: | http://msdn.microsoft.com/
|===

`[MS-OXOAB]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-OXOAB]`: Offline Address Book (OAB) File Format and Schema
| URL: | http://msdn.microsoft.com/
|===

`[MS-OXORULE]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-OXORULE]`: E-Mail Rules Protocol Specification
| URL: | http://msdn.microsoft.com/
|===

`[MS-PST]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-PST]` Outlook Personal Folders File Format (.pst) structure specification
| URL: | http://msdn.microsoft.com/
|===

`[NTLCID]`

[cols="1,5",options="header"]
|===
| Tile: | Locale identifier (LCID) definitions
| URL: | https://github.com/libyal/libfwnt/blob/main/documentation/Language%20Code%20identifiers.asciidoc
|===

`[NTSID]`

[cols="1,5",options="header"]
|===
| Tile: | NT security descriptor definitions
| URL: | https://github.com/libyal/libfwnt/blob/main/documentation/Security%20Descriptor.asciidoc
|===

`[OPENCHANGE]`

[cols="1,5",options="header"]
|===
| Title: | Openchange MAPI library
| URL: | http://www.openchange.org/index.php
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

